-- Imogi employee module, migration 000001.
--
-- UUIDs are generated by the application as UUIDv7 values. Sensitive values
-- are encrypted by the application before they reach PostgreSQL. The database
-- stores ciphertext and keyed lookup hashes, never encryption keys.

-- +goose Up

CREATE SCHEMA IF NOT EXISTS platform;
CREATE SCHEMA IF NOT EXISTS employee;
CREATE SCHEMA IF NOT EXISTS tax;

CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE DOMAIN platform.uuid_v7 AS uuid
CHECK (
    substring(VALUE::text FROM 15 FOR 1) = '7'
    AND substring(VALUE::text FROM 20 FOR 1) IN ('8', '9', 'a', 'b')
);

COMMENT ON DOMAIN platform.uuid_v7 IS
    'Application-generated UUIDv7 identifier. PostgreSQL does not generate IDs for this domain.';

-- +goose StatementBegin
CREATE FUNCTION platform.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := clock_timestamp();
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION platform.prevent_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Hard deletion is not permitted for %.%', TG_TABLE_SCHEMA, TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
END;
$$;
-- +goose StatementEnd

CREATE TABLE employee.employees (
    id                  platform.uuid_v7 PRIMARY KEY,
    employee_number     text NOT NULL,
    nik_ciphertext      bytea NOT NULL,
    nik_lookup_hash     bytea NOT NULL,
    full_name           text NOT NULL,
    birth_place         text,
    birth_date          date,
    gender              text,
    email               text,
    phone               text,
    address             text,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT employees_employee_number_not_blank
        CHECK (btrim(employee_number) <> '' AND char_length(employee_number) <= 100),
    CONSTRAINT employees_full_name_not_blank
        CHECK (btrim(full_name) <> '' AND char_length(full_name) <= 200),
    CONSTRAINT employees_nik_ciphertext_not_empty
        CHECK (octet_length(nik_ciphertext) > 0),
    CONSTRAINT employees_nik_lookup_hash_sha256
        CHECK (octet_length(nik_lookup_hash) = 32),
    CONSTRAINT employees_birth_place_not_blank
        CHECK (birth_place IS NULL OR (btrim(birth_place) <> '' AND char_length(birth_place) <= 200)),
    CONSTRAINT employees_email_length_check
        CHECK (email IS NULL OR char_length(email) <= 320),
    CONSTRAINT employees_phone_length_check
        CHECK (phone IS NULL OR char_length(phone) <= 50),
    CONSTRAINT employees_address_length_check
        CHECK (address IS NULL OR char_length(address) <= 2000),
    CONSTRAINT employees_gender_check
        CHECK (gender IS NULL OR gender IN ('male', 'female', 'unspecified'))
);

COMMENT ON TABLE employee.employees IS
    'Person identity and mutable personal data. NIK is encrypted and indexed only by an application-generated keyed hash.';
COMMENT ON COLUMN employee.employees.employee_number IS
    'Tenant-wide organization employee number; V0 assumes uniqueness across the tenant.';
COMMENT ON COLUMN employee.employees.nik_ciphertext IS
    'Application-encrypted NIK ciphertext. Encryption keys are never stored in PostgreSQL.';
COMMENT ON COLUMN employee.employees.nik_lookup_hash IS
    'Stable HMAC-SHA-256 lookup value for exact-match uniqueness; not a plain hash of NIK.';

CREATE UNIQUE INDEX employees_employee_number_uq
    ON employee.employees (employee_number);

CREATE UNIQUE INDEX employees_nik_lookup_hash_uq
    ON employee.employees (nik_lookup_hash);

CREATE INDEX employees_full_name_trgm_idx
    ON employee.employees USING gin (full_name gin_trgm_ops);

CREATE INDEX employees_employee_number_trgm_idx
    ON employee.employees USING gin (employee_number gin_trgm_ops);

-- +goose StatementBegin
CREATE FUNCTION employee.guard_employee_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.employee_number IS DISTINCT FROM OLD.employee_number THEN
        RAISE EXCEPTION 'Employee number is immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF NEW.nik_lookup_hash IS DISTINCT FROM OLD.nik_lookup_hash THEN
        RAISE EXCEPTION 'Employee NIK identity is immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER employees_guard_update
BEFORE UPDATE ON employee.employees
FOR EACH ROW
EXECUTE FUNCTION employee.guard_employee_update();

CREATE TRIGGER employees_set_updated_at
BEFORE UPDATE ON employee.employees
FOR EACH ROW
EXECUTE FUNCTION platform.set_updated_at();

CREATE TRIGGER employees_prevent_delete
BEFORE DELETE ON employee.employees
FOR EACH ROW
EXECUTE FUNCTION platform.prevent_delete();

CREATE TABLE employee.employments (
    id                  platform.uuid_v7 PRIMARY KEY,
    employee_id         platform.uuid_v7 NOT NULL,
    company_id          platform.uuid_v7 NOT NULL,
    employment_type     text NOT NULL,
    join_date           date NOT NULL,
    end_date            date,
    termination_reason  text,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT employments_employee_fk
        FOREIGN KEY (employee_id)
        REFERENCES employee.employees (id)
        ON DELETE RESTRICT,
    CONSTRAINT employments_type_check
        CHECK (employment_type IN ('permanent', 'non_permanent')),
    CONSTRAINT employments_date_order_check
        CHECK (end_date IS NULL OR end_date >= join_date),
    CONSTRAINT employments_termination_reason_check
        CHECK (
            (end_date IS NULL AND termination_reason IS NULL)
            OR
            (
                end_date IS NOT NULL
                AND termination_reason IS NOT NULL
                AND btrim(termination_reason) <> ''
                AND char_length(termination_reason) <= 100
            )
        ),
    CONSTRAINT employments_end_date_range_check
        CHECK (end_date IS NULL OR end_date < DATE '9999-12-31')
);

COMMENT ON TABLE employee.employments IS
    'One continuous employment relationship. end_date is the inclusive last working date.';
COMMENT ON COLUMN employee.employments.company_id IS
    'References the organization company identity. The organization module owns the referenced table; no cross-module FK is created here.';

CREATE INDEX employments_employee_history_idx
    ON employee.employments (employee_id, join_date DESC);

CREATE INDEX employments_company_history_idx
    ON employee.employments (company_id, join_date DESC);

CREATE UNIQUE INDEX employments_one_open_per_employee_uq
    ON employee.employments (employee_id)
    WHERE end_date IS NULL;

ALTER TABLE employee.employments
    ADD CONSTRAINT employments_no_overlapping_periods
    EXCLUDE USING gist (
        employee_id WITH =,
        daterange(
            join_date,
            CASE
                WHEN end_date IS NULL THEN 'infinity'::date
                ELSE end_date + 1
            END,
            '[)'
        ) WITH &&
    );

-- +goose StatementBegin
CREATE FUNCTION employee.guard_employment_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.employee_id IS DISTINCT FROM OLD.employee_id
       OR NEW.company_id IS DISTINCT FROM OLD.company_id
       OR NEW.employment_type IS DISTINCT FROM OLD.employment_type
       OR NEW.join_date IS DISTINCT FROM OLD.join_date THEN
        RAISE EXCEPTION 'Employment identity and start data are immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.end_date IS NOT NULL
       AND (
           NEW.end_date IS DISTINCT FROM OLD.end_date
           OR NEW.termination_reason IS DISTINCT FROM OLD.termination_reason
       ) THEN
        RAISE EXCEPTION 'Ended employment history is immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER employments_guard_update
BEFORE UPDATE ON employee.employments
FOR EACH ROW
EXECUTE FUNCTION employee.guard_employment_update();

CREATE TRIGGER employments_set_updated_at
BEFORE UPDATE ON employee.employments
FOR EACH ROW
EXECUTE FUNCTION platform.set_updated_at();

CREATE TRIGGER employments_prevent_delete
BEFORE DELETE ON employee.employments
FOR EACH ROW
EXECUTE FUNCTION platform.prevent_delete();

CREATE TABLE employee.employee_assignments (
    id                  platform.uuid_v7 PRIMARY KEY,
    employment_id       platform.uuid_v7 NOT NULL,
    location_id         platform.uuid_v7,
    department_id       platform.uuid_v7,
    position_id         platform.uuid_v7,
    group_id            platform.uuid_v7,
    effective_from      date NOT NULL,
    effective_to        date,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT employee_assignments_employment_fk
        FOREIGN KEY (employment_id)
        REFERENCES employee.employments (id)
        ON DELETE RESTRICT,
    CONSTRAINT employee_assignments_one_unit_check
        CHECK (
            location_id IS NOT NULL
            OR department_id IS NOT NULL
            OR position_id IS NOT NULL
            OR group_id IS NOT NULL
        ),
    CONSTRAINT employee_assignments_date_order_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT employee_assignments_end_date_range_check
        CHECK (effective_to IS NULL OR effective_to < DATE '9999-12-31')
);

COMMENT ON TABLE employee.employee_assignments IS
    'Effective-dated organizational placement. effective_to is inclusive; a new assignment closes the preceding assignment at the previous day.';
COMMENT ON COLUMN employee.employee_assignments.location_id IS
    'References an organization-managed location. No FK is created until the organization schema is available.';
COMMENT ON COLUMN employee.employee_assignments.department_id IS
    'References an organization-managed department. No FK is created until the organization schema is available.';
COMMENT ON COLUMN employee.employee_assignments.position_id IS
    'References an organization-managed position. No FK is created until the organization schema is available.';
COMMENT ON COLUMN employee.employee_assignments.group_id IS
    'References an organization-managed group. No FK is created until the organization schema is available.';

CREATE INDEX employee_assignments_history_idx
    ON employee.employee_assignments (employment_id, effective_from DESC);

CREATE UNIQUE INDEX employee_assignments_one_open_uq
    ON employee.employee_assignments (employment_id)
    WHERE effective_to IS NULL;

ALTER TABLE employee.employee_assignments
    ADD CONSTRAINT employee_assignments_no_overlapping_periods
    EXCLUDE USING gist (
        employment_id WITH =,
        daterange(
            effective_from,
            CASE
                WHEN effective_to IS NULL THEN 'infinity'::date
                ELSE effective_to + 1
            END,
            '[)'
        ) WITH &&
    );

-- +goose StatementBegin
CREATE FUNCTION employee.guard_assignment_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.employment_id IS DISTINCT FROM OLD.employment_id
       OR NEW.location_id IS DISTINCT FROM OLD.location_id
       OR NEW.department_id IS DISTINCT FROM OLD.department_id
       OR NEW.position_id IS DISTINCT FROM OLD.position_id
       OR NEW.group_id IS DISTINCT FROM OLD.group_id
       OR NEW.effective_from IS DISTINCT FROM OLD.effective_from THEN
        RAISE EXCEPTION 'Assignment history is immutable; create a new assignment instead'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.effective_to IS NOT NULL
       AND NEW.effective_to IS DISTINCT FROM OLD.effective_to THEN
        RAISE EXCEPTION 'Closed assignment history is immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER employee_assignments_guard_update
BEFORE UPDATE ON employee.employee_assignments
FOR EACH ROW
EXECUTE FUNCTION employee.guard_assignment_update();

CREATE TRIGGER employee_assignments_set_updated_at
BEFORE UPDATE ON employee.employee_assignments
FOR EACH ROW
EXECUTE FUNCTION platform.set_updated_at();

CREATE TRIGGER employee_assignments_prevent_delete
BEFORE DELETE ON employee.employee_assignments
FOR EACH ROW
EXECUTE FUNCTION platform.prevent_delete();

-- +goose StatementBegin
CREATE FUNCTION employee.validate_assignment_period()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    employment_join_date date;
    employment_end_date date;
BEGIN
    IF TG_TABLE_NAME = 'employments' THEN
        IF EXISTS (
            SELECT 1
            FROM employee.employee_assignments a
            WHERE a.employment_id = NEW.id
              AND (
                  a.effective_from < NEW.join_date
                  OR (
                      NEW.end_date IS NOT NULL
                      AND (a.effective_to IS NULL OR a.effective_to > NEW.end_date)
                  )
              )
        ) THEN
            RAISE EXCEPTION 'Assignment period must remain within its employment period'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
    ELSE
        SELECT e.join_date, e.end_date
        INTO employment_join_date, employment_end_date
        FROM employee.employments e
        WHERE e.id = NEW.employment_id;

        IF employment_join_date IS NULL THEN
            RAISE EXCEPTION 'Assignment references a missing employment'
                USING ERRCODE = 'foreign_key_violation';
        END IF;

        IF NEW.effective_from < employment_join_date
           OR (
               employment_end_date IS NOT NULL
               AND (NEW.effective_to IS NULL OR NEW.effective_to > employment_end_date)
           ) THEN
            RAISE EXCEPTION 'Assignment period must remain within its employment period'
                USING ERRCODE = 'integrity_constraint_violation';
        END IF;
    END IF;

    RETURN NULL;
END;
$$;
-- +goose StatementEnd

CREATE CONSTRAINT TRIGGER employee_assignments_fit_employment
AFTER INSERT OR UPDATE ON employee.employee_assignments
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION employee.validate_assignment_period();

CREATE CONSTRAINT TRIGGER employments_contain_assignments
AFTER UPDATE ON employee.employments
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION employee.validate_assignment_period();

CREATE TABLE tax.employee_tax_profiles (
    id                  platform.uuid_v7 PRIMARY KEY,
    employee_id         platform.uuid_v7 NOT NULL,
    nik_ciphertext      bytea NOT NULL,
    npwp_ciphertext     bytea,
    ptkp_code            text NOT NULL,
    tax_method          text NOT NULL,
    effective_from      date NOT NULL,
    effective_to        date,
    created_at          timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at          timestamptz NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT employee_tax_profiles_employee_fk
        FOREIGN KEY (employee_id)
        REFERENCES employee.employees (id)
        ON DELETE RESTRICT,
    CONSTRAINT employee_tax_profiles_nik_ciphertext_not_empty
        CHECK (octet_length(nik_ciphertext) > 0),
    CONSTRAINT employee_tax_profiles_npwp_ciphertext_check
        CHECK (npwp_ciphertext IS NULL OR octet_length(npwp_ciphertext) > 0),
    CONSTRAINT employee_tax_profiles_ptkp_code_check
        CHECK (btrim(ptkp_code) <> '' AND char_length(ptkp_code) <= 20),
    CONSTRAINT employee_tax_profiles_tax_method_check
        CHECK (btrim(tax_method) <> '' AND char_length(tax_method) <= 50),
    CONSTRAINT employee_tax_profiles_date_order_check
        CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT employee_tax_profiles_end_date_range_check
        CHECK (effective_to IS NULL OR effective_to < DATE '9999-12-31'),
    CONSTRAINT employee_tax_profiles_effective_start_uq
        UNIQUE (employee_id, effective_from)
);

COMMENT ON TABLE tax.employee_tax_profiles IS
    'Historical tax profile snapshots. Profile values are encrypted and are never recalculated from current employee data.';
COMMENT ON COLUMN tax.employee_tax_profiles.nik_ciphertext IS
    'Encrypted NIK snapshot effective for this tax profile period.';
COMMENT ON COLUMN tax.employee_tax_profiles.npwp_ciphertext IS
    'Encrypted NPWP snapshot effective for this tax profile period.';
COMMENT ON COLUMN tax.employee_tax_profiles.effective_to IS
    'Inclusive end date. A new profile closes the prior open profile at the previous day.';

CREATE INDEX employee_tax_profiles_history_idx
    ON tax.employee_tax_profiles (employee_id, effective_from DESC);

ALTER TABLE tax.employee_tax_profiles
    ADD CONSTRAINT employee_tax_profiles_no_overlapping_periods
    EXCLUDE USING gist (
        employee_id WITH =,
        daterange(
            effective_from,
            CASE
                WHEN effective_to IS NULL THEN 'infinity'::date
                ELSE effective_to + 1
            END,
            '[)'
        ) WITH &&
    );

-- +goose StatementBegin
CREATE FUNCTION tax.guard_tax_profile_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.employee_id IS DISTINCT FROM OLD.employee_id
       OR NEW.nik_ciphertext IS DISTINCT FROM OLD.nik_ciphertext
       OR NEW.npwp_ciphertext IS DISTINCT FROM OLD.npwp_ciphertext
       OR NEW.ptkp_code IS DISTINCT FROM OLD.ptkp_code
       OR NEW.tax_method IS DISTINCT FROM OLD.tax_method
       OR NEW.effective_from IS DISTINCT FROM OLD.effective_from THEN
        RAISE EXCEPTION 'Tax profile history is immutable; create a new profile instead'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    IF OLD.effective_to IS NOT NULL
       AND NEW.effective_to IS DISTINCT FROM OLD.effective_to THEN
        RAISE EXCEPTION 'Closed tax profile history is immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER employee_tax_profiles_guard_update
BEFORE UPDATE ON tax.employee_tax_profiles
FOR EACH ROW
EXECUTE FUNCTION tax.guard_tax_profile_update();

CREATE TRIGGER employee_tax_profiles_set_updated_at
BEFORE UPDATE ON tax.employee_tax_profiles
FOR EACH ROW
EXECUTE FUNCTION platform.set_updated_at();

CREATE TRIGGER employee_tax_profiles_prevent_delete
BEFORE DELETE ON tax.employee_tax_profiles
FOR EACH ROW
EXECUTE FUNCTION platform.prevent_delete();


-- +goose Down

DROP TABLE IF EXISTS tax.employee_tax_profiles;
DROP TABLE IF EXISTS employee.employee_assignments;
DROP TABLE IF EXISTS employee.employments;
DROP TABLE IF EXISTS employee.employees;

DROP FUNCTION IF EXISTS tax.guard_tax_profile_update();
DROP FUNCTION IF EXISTS employee.validate_assignment_period();
DROP FUNCTION IF EXISTS employee.guard_assignment_update();
DROP FUNCTION IF EXISTS employee.guard_employment_update();
DROP FUNCTION IF EXISTS employee.guard_employee_update();
DROP FUNCTION IF EXISTS platform.prevent_delete();
DROP FUNCTION IF EXISTS platform.set_updated_at();

DROP DOMAIN IF EXISTS platform.uuid_v7;
DROP SCHEMA IF EXISTS tax;
DROP SCHEMA IF EXISTS employee;
DROP SCHEMA IF EXISTS platform;
