// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employee.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeAssignment = `-- name: CloseAssignment :one
UPDATE employee.employee_assignments
SET effective_to = $1
WHERE id = $2
  AND effective_to IS NULL
RETURNING id, employment_id, location_id, department_id, position_id, group_id, effective_from, effective_to, created_at, updated_at
`

type CloseAssignmentParams struct {
	EffectiveTo pgtype.Date `json:"effective_to"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) CloseAssignment(ctx context.Context, arg CloseAssignmentParams) (EmployeeEmployeeAssignment, error) {
	row := q.db.QueryRow(ctx, closeAssignment, arg.EffectiveTo, arg.ID)
	var i EmployeeEmployeeAssignment
	err := row.Scan(
		&i.ID,
		&i.EmploymentID,
		&i.LocationID,
		&i.DepartmentID,
		&i.PositionID,
		&i.GroupID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeTaxProfile = `-- name: CloseTaxProfile :one
UPDATE tax.employee_tax_profiles
SET effective_to = $1
WHERE id = $2
  AND effective_to IS NULL
RETURNING id, employee_id, nik_ciphertext, npwp_ciphertext, ptkp_code, tax_method, effective_from, effective_to, created_at, updated_at, tenant_id, company_id
`

type CloseTaxProfileParams struct {
	EffectiveTo pgtype.Date `json:"effective_to"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) CloseTaxProfile(ctx context.Context, arg CloseTaxProfileParams) (TaxEmployeeTaxProfile, error) {
	row := q.db.QueryRow(ctx, closeTaxProfile, arg.EffectiveTo, arg.ID)
	var i TaxEmployeeTaxProfile
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.NikCiphertext,
		&i.NpwpCiphertext,
		&i.PtkpCode,
		&i.TaxMethod,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.CompanyID,
	)
	return i, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO employee.employee_assignments (
    id,
    employment_id,
    location_id,
    department_id,
    position_id,
    group_id,
    effective_from
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, employment_id, location_id, department_id, position_id, group_id, effective_from, effective_to, created_at, updated_at
`

type CreateAssignmentParams struct {
	ID            uuid.UUID   `json:"id"`
	EmploymentID  uuid.UUID   `json:"employment_id"`
	LocationID    *uuid.UUID  `json:"location_id"`
	DepartmentID  *uuid.UUID  `json:"department_id"`
	PositionID    *uuid.UUID  `json:"position_id"`
	GroupID       *uuid.UUID  `json:"group_id"`
	EffectiveFrom pgtype.Date `json:"effective_from"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (EmployeeEmployeeAssignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.ID,
		arg.EmploymentID,
		arg.LocationID,
		arg.DepartmentID,
		arg.PositionID,
		arg.GroupID,
		arg.EffectiveFrom,
	)
	var i EmployeeEmployeeAssignment
	err := row.Scan(
		&i.ID,
		&i.EmploymentID,
		&i.LocationID,
		&i.DepartmentID,
		&i.PositionID,
		&i.GroupID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employee.employees (
    id,
    tenant_id,
    company_id,
    employee_number,
    nik_ciphertext,
    nik_lookup_hash,
    full_name,
    birth_place,
    birth_date,
    gender,
    email,
    phone,
    address
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, employee_number, nik_ciphertext, nik_lookup_hash, full_name, birth_place, birth_date, gender, email, phone, address, created_at, updated_at, tenant_id, company_id
`

type CreateEmployeeParams struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	CompanyID      uuid.UUID   `json:"company_id"`
	EmployeeNumber string      `json:"employee_number"`
	NikCiphertext  []byte      `json:"nik_ciphertext"`
	NikLookupHash  []byte      `json:"nik_lookup_hash"`
	FullName       string      `json:"full_name"`
	BirthPlace     *string     `json:"birth_place"`
	BirthDate      pgtype.Date `json:"birth_date"`
	Gender         *string     `json:"gender"`
	Email          *string     `json:"email"`
	Phone          *string     `json:"phone"`
	Address        *string     `json:"address"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (EmployeeEmployee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.EmployeeNumber,
		arg.NikCiphertext,
		arg.NikLookupHash,
		arg.FullName,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Gender,
		arg.Email,
		arg.Phone,
		arg.Address,
	)
	var i EmployeeEmployee
	err := row.Scan(
		&i.ID,
		&i.EmployeeNumber,
		&i.NikCiphertext,
		&i.NikLookupHash,
		&i.FullName,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.CompanyID,
	)
	return i, err
}

const createEmployment = `-- name: CreateEmployment :one
INSERT INTO employee.employments (
    id,
    employee_id,
    tenant_id,
    company_id,
    employment_type,
    join_date
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, employee_id, company_id, employment_type, join_date, end_date, termination_reason, created_at, updated_at, tenant_id
`

type CreateEmploymentParams struct {
	ID             uuid.UUID   `json:"id"`
	EmployeeID     uuid.UUID   `json:"employee_id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	CompanyID      uuid.UUID   `json:"company_id"`
	EmploymentType string      `json:"employment_type"`
	JoinDate       pgtype.Date `json:"join_date"`
}

func (q *Queries) CreateEmployment(ctx context.Context, arg CreateEmploymentParams) (EmployeeEmployment, error) {
	row := q.db.QueryRow(ctx, createEmployment,
		arg.ID,
		arg.EmployeeID,
		arg.TenantID,
		arg.CompanyID,
		arg.EmploymentType,
		arg.JoinDate,
	)
	var i EmployeeEmployment
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.EmploymentType,
		&i.JoinDate,
		&i.EndDate,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const createTaxProfile = `-- name: CreateTaxProfile :one
INSERT INTO tax.employee_tax_profiles (
    id,
    employee_id,
    tenant_id,
    company_id,
    nik_ciphertext,
    npwp_ciphertext,
    ptkp_code,
    tax_method,
    effective_from
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, employee_id, nik_ciphertext, npwp_ciphertext, ptkp_code, tax_method, effective_from, effective_to, created_at, updated_at, tenant_id, company_id
`

type CreateTaxProfileParams struct {
	ID             uuid.UUID   `json:"id"`
	EmployeeID     uuid.UUID   `json:"employee_id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	CompanyID      uuid.UUID   `json:"company_id"`
	NikCiphertext  []byte      `json:"nik_ciphertext"`
	NpwpCiphertext []byte      `json:"npwp_ciphertext"`
	PtkpCode       string      `json:"ptkp_code"`
	TaxMethod      string      `json:"tax_method"`
	EffectiveFrom  pgtype.Date `json:"effective_from"`
}

func (q *Queries) CreateTaxProfile(ctx context.Context, arg CreateTaxProfileParams) (TaxEmployeeTaxProfile, error) {
	row := q.db.QueryRow(ctx, createTaxProfile,
		arg.ID,
		arg.EmployeeID,
		arg.TenantID,
		arg.CompanyID,
		arg.NikCiphertext,
		arg.NpwpCiphertext,
		arg.PtkpCode,
		arg.TaxMethod,
		arg.EffectiveFrom,
	)
	var i TaxEmployeeTaxProfile
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.NikCiphertext,
		&i.NpwpCiphertext,
		&i.PtkpCode,
		&i.TaxMethod,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.CompanyID,
	)
	return i, err
}

const endEmployment = `-- name: EndEmployment :one
UPDATE employee.employments
SET
    end_date = $1,
    termination_reason = $2
WHERE id = $3
  AND end_date IS NULL
RETURNING id, employee_id, company_id, employment_type, join_date, end_date, termination_reason, created_at, updated_at, tenant_id
`

type EndEmploymentParams struct {
	EndDate           pgtype.Date `json:"end_date"`
	TerminationReason *string     `json:"termination_reason"`
	ID                uuid.UUID   `json:"id"`
}

func (q *Queries) EndEmployment(ctx context.Context, arg EndEmploymentParams) (EmployeeEmployment, error) {
	row := q.db.QueryRow(ctx, endEmployment, arg.EndDate, arg.TerminationReason, arg.ID)
	var i EmployeeEmployment
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.EmploymentType,
		&i.JoinDate,
		&i.EndDate,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const findOpenAssignmentByEmploymentForUpdate = `-- name: FindOpenAssignmentByEmploymentForUpdate :one
SELECT id, employment_id, location_id, department_id, position_id, group_id, effective_from, effective_to, created_at, updated_at
FROM employee.employee_assignments
WHERE employment_id = $1
  AND effective_to IS NULL
FOR UPDATE
`

func (q *Queries) FindOpenAssignmentByEmploymentForUpdate(ctx context.Context, employmentID uuid.UUID) (EmployeeEmployeeAssignment, error) {
	row := q.db.QueryRow(ctx, findOpenAssignmentByEmploymentForUpdate, employmentID)
	var i EmployeeEmployeeAssignment
	err := row.Scan(
		&i.ID,
		&i.EmploymentID,
		&i.LocationID,
		&i.DepartmentID,
		&i.PositionID,
		&i.GroupID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOpenEmploymentByEmployeeForUpdate = `-- name: FindOpenEmploymentByEmployeeForUpdate :one
SELECT id, employee_id, company_id, employment_type, join_date, end_date, termination_reason, created_at, updated_at, tenant_id
FROM employee.employments
WHERE employee_id = $1
  AND end_date IS NULL
FOR UPDATE
`

func (q *Queries) FindOpenEmploymentByEmployeeForUpdate(ctx context.Context, employeeID uuid.UUID) (EmployeeEmployment, error) {
	row := q.db.QueryRow(ctx, findOpenEmploymentByEmployeeForUpdate, employeeID)
	var i EmployeeEmployment
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.EmploymentType,
		&i.JoinDate,
		&i.EndDate,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const findOpenTaxProfileByEmployeeForUpdate = `-- name: FindOpenTaxProfileByEmployeeForUpdate :one
SELECT id, employee_id, nik_ciphertext, npwp_ciphertext, ptkp_code, tax_method, effective_from, effective_to, created_at, updated_at, tenant_id, company_id
FROM tax.employee_tax_profiles
WHERE employee_id = $1
  AND effective_to IS NULL
FOR UPDATE
`

func (q *Queries) FindOpenTaxProfileByEmployeeForUpdate(ctx context.Context, employeeID uuid.UUID) (TaxEmployeeTaxProfile, error) {
	row := q.db.QueryRow(ctx, findOpenTaxProfileByEmployeeForUpdate, employeeID)
	var i TaxEmployeeTaxProfile
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.NikCiphertext,
		&i.NpwpCiphertext,
		&i.PtkpCode,
		&i.TaxMethod,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.CompanyID,
	)
	return i, err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, employment_id, location_id, department_id, position_id, group_id, effective_from, effective_to, created_at, updated_at
FROM employee.employee_assignments
WHERE id = $1
`

func (q *Queries) GetAssignment(ctx context.Context, id uuid.UUID) (EmployeeEmployeeAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i EmployeeEmployeeAssignment
	err := row.Scan(
		&i.ID,
		&i.EmploymentID,
		&i.LocationID,
		&i.DepartmentID,
		&i.PositionID,
		&i.GroupID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, employee_number, nik_ciphertext, nik_lookup_hash, full_name, birth_place, birth_date, gender, email, phone, address, created_at, updated_at, tenant_id, company_id
FROM employee.employees
WHERE id = $1
`

func (q *Queries) GetEmployee(ctx context.Context, id uuid.UUID) (EmployeeEmployee, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i EmployeeEmployee
	err := row.Scan(
		&i.ID,
		&i.EmployeeNumber,
		&i.NikCiphertext,
		&i.NikLookupHash,
		&i.FullName,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.CompanyID,
	)
	return i, err
}

const getEmployment = `-- name: GetEmployment :one
SELECT id, employee_id, company_id, employment_type, join_date, end_date, termination_reason, created_at, updated_at, tenant_id
FROM employee.employments
WHERE id = $1
`

func (q *Queries) GetEmployment(ctx context.Context, id uuid.UUID) (EmployeeEmployment, error) {
	row := q.db.QueryRow(ctx, getEmployment, id)
	var i EmployeeEmployment
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.EmploymentType,
		&i.JoinDate,
		&i.EndDate,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getEmploymentForUpdate = `-- name: GetEmploymentForUpdate :one
SELECT id, employee_id, company_id, employment_type, join_date, end_date, termination_reason, created_at, updated_at, tenant_id
FROM employee.employments
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetEmploymentForUpdate(ctx context.Context, id uuid.UUID) (EmployeeEmployment, error) {
	row := q.db.QueryRow(ctx, getEmploymentForUpdate, id)
	var i EmployeeEmployment
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.EmploymentType,
		&i.JoinDate,
		&i.EndDate,
		&i.TerminationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getTaxProfile = `-- name: GetTaxProfile :one
SELECT id, employee_id, nik_ciphertext, npwp_ciphertext, ptkp_code, tax_method, effective_from, effective_to, created_at, updated_at, tenant_id, company_id
FROM tax.employee_tax_profiles
WHERE id = $1
`

func (q *Queries) GetTaxProfile(ctx context.Context, id uuid.UUID) (TaxEmployeeTaxProfile, error) {
	row := q.db.QueryRow(ctx, getTaxProfile, id)
	var i TaxEmployeeTaxProfile
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.NikCiphertext,
		&i.NpwpCiphertext,
		&i.PtkpCode,
		&i.TaxMethod,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.CompanyID,
	)
	return i, err
}

const listAssignmentsByEmployment = `-- name: ListAssignmentsByEmployment :many
SELECT id, employment_id, location_id, department_id, position_id, group_id, effective_from, effective_to, created_at, updated_at
FROM employee.employee_assignments
WHERE employment_id = $1
ORDER BY effective_from DESC, id DESC
`

func (q *Queries) ListAssignmentsByEmployment(ctx context.Context, employmentID uuid.UUID) ([]EmployeeEmployeeAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByEmployment, employmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeEmployeeAssignment
	for rows.Next() {
		var i EmployeeEmployeeAssignment
		if err := rows.Scan(
			&i.ID,
			&i.EmploymentID,
			&i.LocationID,
			&i.DepartmentID,
			&i.PositionID,
			&i.GroupID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeSummaries = `-- name: ListEmployeeSummaries :many
SELECT id, tenant_id, company_id, employee_number, full_name, created_at, updated_at
FROM employee.employees
WHERE (
    $1::text IS NULL
    OR full_name ILIKE '%' || $1::text || '%'
    OR employee_number ILIKE '%' || $1::text || '%'
)
AND (
    $2::platform.uuid_v7 IS NULL
    OR tenant_id = $2::platform.uuid_v7
)
AND (
    $3::platform.uuid_v7 IS NULL
    OR company_id = $3::platform.uuid_v7
)
AND (
    $4::platform.uuid_v7 IS NULL
    OR id < $4::platform.uuid_v7
)
AND (
    $5::text IS NULL
    OR (
        $5::text = 'active'
        AND EXISTS (
            SELECT 1 FROM employee.employments e
            WHERE e.employee_id = employee.employees.id
              AND e.join_date <= CURRENT_DATE
              AND (e.end_date IS NULL OR e.end_date >= CURRENT_DATE)
        )
    )
    OR (
        $5::text = 'scheduled'
        AND EXISTS (
            SELECT 1 FROM employee.employments e
            WHERE e.employee_id = employee.employees.id
              AND e.join_date > CURRENT_DATE
              AND e.end_date IS NULL
        )
    )
    OR (
        $5::text = 'ended'
        AND NOT EXISTS (
            SELECT 1 FROM employee.employments e
            WHERE e.employee_id = employee.employees.id
              AND e.end_date IS NULL
        )
        AND EXISTS (
            SELECT 1 FROM employee.employments e
            WHERE e.employee_id = employee.employees.id
        )
    )
)
ORDER BY id DESC
LIMIT $6
`

type ListEmployeeSummariesParams struct {
	Search           *string    `json:"search"`
	TenantID         *uuid.UUID `json:"tenant_id"`
	CompanyID        *uuid.UUID `json:"company_id"`
	CursorID         *uuid.UUID `json:"cursor_id"`
	EmploymentStatus *string    `json:"employment_status"`
	Limit            int32      `json:"limit"`
}

type ListEmployeeSummariesRow struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	EmployeeNumber string             `json:"employee_number"`
	FullName       string             `json:"full_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEmployeeSummaries(ctx context.Context, arg ListEmployeeSummariesParams) ([]ListEmployeeSummariesRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeSummaries,
		arg.Search,
		arg.TenantID,
		arg.CompanyID,
		arg.CursorID,
		arg.EmploymentStatus,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeSummariesRow
	for rows.Next() {
		var i ListEmployeeSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyID,
			&i.EmployeeNumber,
			&i.FullName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmploymentsByEmployee = `-- name: ListEmploymentsByEmployee :many
SELECT id, employee_id, company_id, employment_type, join_date, end_date, termination_reason, created_at, updated_at, tenant_id
FROM employee.employments
WHERE employee_id = $1
ORDER BY join_date DESC, id DESC
`

func (q *Queries) ListEmploymentsByEmployee(ctx context.Context, employeeID uuid.UUID) ([]EmployeeEmployment, error) {
	rows, err := q.db.Query(ctx, listEmploymentsByEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeEmployment
	for rows.Next() {
		var i EmployeeEmployment
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.CompanyID,
			&i.EmploymentType,
			&i.JoinDate,
			&i.EndDate,
			&i.TerminationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxProfilesByEmployee = `-- name: ListTaxProfilesByEmployee :many
SELECT id, employee_id, nik_ciphertext, npwp_ciphertext, ptkp_code, tax_method, effective_from, effective_to, created_at, updated_at, tenant_id, company_id
FROM tax.employee_tax_profiles
WHERE employee_id = $1
ORDER BY effective_from DESC, id DESC
`

func (q *Queries) ListTaxProfilesByEmployee(ctx context.Context, employeeID uuid.UUID) ([]TaxEmployeeTaxProfile, error) {
	rows, err := q.db.Query(ctx, listTaxProfilesByEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxEmployeeTaxProfile
	for rows.Next() {
		var i TaxEmployeeTaxProfile
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.NikCiphertext,
			&i.NpwpCiphertext,
			&i.PtkpCode,
			&i.TaxMethod,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeePersonalData = `-- name: UpdateEmployeePersonalData :one
UPDATE employee.employees
SET
    full_name = $1,
    birth_place = $2,
    birth_date = $3,
    gender = $4,
    email = $5,
    phone = $6,
    address = $7
WHERE id = $8
RETURNING id, employee_number, nik_ciphertext, nik_lookup_hash, full_name, birth_place, birth_date, gender, email, phone, address, created_at, updated_at, tenant_id, company_id
`

type UpdateEmployeePersonalDataParams struct {
	FullName   string      `json:"full_name"`
	BirthPlace *string     `json:"birth_place"`
	BirthDate  pgtype.Date `json:"birth_date"`
	Gender     *string     `json:"gender"`
	Email      *string     `json:"email"`
	Phone      *string     `json:"phone"`
	Address    *string     `json:"address"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateEmployeePersonalData(ctx context.Context, arg UpdateEmployeePersonalDataParams) (EmployeeEmployee, error) {
	row := q.db.QueryRow(ctx, updateEmployeePersonalData,
		arg.FullName,
		arg.BirthPlace,
		arg.BirthDate,
		arg.Gender,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.ID,
	)
	var i EmployeeEmployee
	err := row.Scan(
		&i.ID,
		&i.EmployeeNumber,
		&i.NikCiphertext,
		&i.NikLookupHash,
		&i.FullName,
		&i.BirthPlace,
		&i.BirthDate,
		&i.Gender,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.CompanyID,
	)
	return i, err
}
