// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: employee_number_history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeOpenEmployeeNumberHistory = `-- name: CloseOpenEmployeeNumberHistory :exec
UPDATE employee.employee_number_history
SET effective_to = $1
WHERE employee_id = $2
  AND effective_to IS NULL
  AND effective_from < $3
`

type CloseOpenEmployeeNumberHistoryParams struct {
	EffectiveTo   pgtype.Date `json:"effective_to"`
	EmployeeID    uuid.UUID   `json:"employee_id"`
	EffectiveFrom pgtype.Date `json:"effective_from"`
}

func (q *Queries) CloseOpenEmployeeNumberHistory(ctx context.Context, arg CloseOpenEmployeeNumberHistoryParams) error {
	_, err := q.db.Exec(ctx, closeOpenEmployeeNumberHistory, arg.EffectiveTo, arg.EmployeeID, arg.EffectiveFrom)
	return err
}

const createEmployeeNumberHistory = `-- name: CreateEmployeeNumberHistory :one
INSERT INTO employee.employee_number_history (
    id, tenant_id, company_id, employee_id, employment_id, employee_number,
    number_type, effective_from, effective_to, source, source_batch_id,
    supersedes_id, correction_reason, created_by
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14
)
RETURNING id, tenant_id, company_id, employee_id, employment_id, employee_number, number_type, effective_from, effective_to, source, source_batch_id, supersedes_id, correction_reason, created_by, created_at
`

type CreateEmployeeNumberHistoryParams struct {
	ID               uuid.UUID   `json:"id"`
	TenantID         uuid.UUID   `json:"tenant_id"`
	CompanyID        uuid.UUID   `json:"company_id"`
	EmployeeID       uuid.UUID   `json:"employee_id"`
	EmploymentID     *uuid.UUID  `json:"employment_id"`
	EmployeeNumber   string      `json:"employee_number"`
	NumberType       string      `json:"number_type"`
	EffectiveFrom    pgtype.Date `json:"effective_from"`
	EffectiveTo      pgtype.Date `json:"effective_to"`
	Source           string      `json:"source"`
	SourceBatchID    *uuid.UUID  `json:"source_batch_id"`
	SupersedesID     *uuid.UUID  `json:"supersedes_id"`
	CorrectionReason *string     `json:"correction_reason"`
	CreatedBy        *uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateEmployeeNumberHistory(ctx context.Context, arg CreateEmployeeNumberHistoryParams) (EmployeeEmployeeNumberHistory, error) {
	row := q.db.QueryRow(ctx, createEmployeeNumberHistory,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.EmployeeID,
		arg.EmploymentID,
		arg.EmployeeNumber,
		arg.NumberType,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Source,
		arg.SourceBatchID,
		arg.SupersedesID,
		arg.CorrectionReason,
		arg.CreatedBy,
	)
	var i EmployeeEmployeeNumberHistory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.EmploymentID,
		&i.EmployeeNumber,
		&i.NumberType,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Source,
		&i.SourceBatchID,
		&i.SupersedesID,
		&i.CorrectionReason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEmployeeNumberHistory = `-- name: ListEmployeeNumberHistory :many
SELECT id, tenant_id, company_id, employee_id, employment_id, employee_number, number_type, effective_from, effective_to, source, source_batch_id, supersedes_id, correction_reason, created_by, created_at
FROM employee.employee_number_history
WHERE employee_id = $1
ORDER BY effective_from DESC, id DESC
`

func (q *Queries) ListEmployeeNumberHistory(ctx context.Context, employeeID uuid.UUID) ([]EmployeeEmployeeNumberHistory, error) {
	rows, err := q.db.Query(ctx, listEmployeeNumberHistory, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeEmployeeNumberHistory
	for rows.Next() {
		var i EmployeeEmployeeNumberHistory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.EmploymentID,
			&i.EmployeeNumber,
			&i.NumberType,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Source,
			&i.SourceBatchID,
			&i.SupersedesID,
			&i.CorrectionReason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
