// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file_batches.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBackgroundJobsForBatch = `-- name: CancelBackgroundJobsForBatch :exec
UPDATE platform.background_jobs AS job
SET status = CASE
        WHEN job.status IN ('queued', 'retry_scheduled') THEN 'canceled'
        ELSE 'cancel_requested'
    END,
    completed_at = CASE
        WHEN job.status IN ('queued', 'retry_scheduled') THEN clock_timestamp()
        ELSE job.completed_at
    END
FROM file.import_batch_steps AS step
WHERE step.batch_id = $1
  AND step.job_id = job.id
  AND job.status IN ('queued', 'retry_scheduled', 'running')
`

func (q *Queries) CancelBackgroundJobsForBatch(ctx context.Context, batchID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelBackgroundJobsForBatch, batchID)
	return err
}

const createBatchArtifact = `-- name: CreateBatchArtifact :one
INSERT INTO file.batch_artifacts (id, batch_id, file_object_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, batch_id, file_object_id, role, created_at
`

type CreateBatchArtifactParams struct {
	ID           uuid.UUID `json:"id"`
	BatchID      uuid.UUID `json:"batch_id"`
	FileObjectID uuid.UUID `json:"file_object_id"`
	Role         string    `json:"role"`
}

func (q *Queries) CreateBatchArtifact(ctx context.Context, arg CreateBatchArtifactParams) (FileBatchArtifact, error) {
	row := q.db.QueryRow(ctx, createBatchArtifact,
		arg.ID,
		arg.BatchID,
		arg.FileObjectID,
		arg.Role,
	)
	var i FileBatchArtifact
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.FileObjectID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createFileObject = `-- name: CreateFileObject :one
INSERT INTO file.file_objects (
    id, tenant_id, company_id, storage_provider, object_key, original_filename,
    detected_extension, detected_mime_type, size_bytes, sha256, encryption_mode,
    status, expires_at, created_by
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14
)
RETURNING id, tenant_id, company_id, storage_provider, object_key, original_filename, detected_extension, detected_mime_type, size_bytes, sha256, encryption_mode, status, expires_at, legal_hold, created_by, created_at, updated_at
`

type CreateFileObjectParams struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          *uuid.UUID         `json:"tenant_id"`
	CompanyID         *uuid.UUID         `json:"company_id"`
	StorageProvider   string             `json:"storage_provider"`
	ObjectKey         string             `json:"object_key"`
	OriginalFilename  string             `json:"original_filename"`
	DetectedExtension string             `json:"detected_extension"`
	DetectedMimeType  string             `json:"detected_mime_type"`
	SizeBytes         int64              `json:"size_bytes"`
	Sha256            []byte             `json:"sha256"`
	EncryptionMode    string             `json:"encryption_mode"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedBy         *uuid.UUID         `json:"created_by"`
}

func (q *Queries) CreateFileObject(ctx context.Context, arg CreateFileObjectParams) (FileFileObject, error) {
	row := q.db.QueryRow(ctx, createFileObject,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.StorageProvider,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.DetectedExtension,
		arg.DetectedMimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.EncryptionMode,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i FileFileObject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.DetectedExtension,
		&i.DetectedMimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.EncryptionMode,
		&i.Status,
		&i.ExpiresAt,
		&i.LegalHold,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO file.import_batches (
    id, tenant_id, company_id, operation, input_file_id, template_id, created_by, expires_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, tenant_id, company_id, operation, input_file_id, template_id, created_by, status, total_rows, valid_rows, invalid_rows, warning_rows, committed_rows, rejected_rows, validation_started_at, validation_finished_at, commit_started_at, commit_finished_at, expires_at, created_at, updated_at
`

type CreateImportBatchParams struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	Operation   string             `json:"operation"`
	InputFileID uuid.UUID          `json:"input_file_id"`
	TemplateID  *uuid.UUID         `json:"template_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (FileImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.Operation,
		arg.InputFileID,
		arg.TemplateID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i FileImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Operation,
		&i.InputFileID,
		&i.TemplateID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.WarningRows,
		&i.CommittedRows,
		&i.RejectedRows,
		&i.ValidationStartedAt,
		&i.ValidationFinishedAt,
		&i.CommitStartedAt,
		&i.CommitFinishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportBatchStep = `-- name: CreateImportBatchStep :one
INSERT INTO file.import_batch_steps (id, batch_id, step_type, job_id)
VALUES ($1, $2, $3, $4)
RETURNING id, batch_id, step_type, job_id, status, created_at, started_at, finished_at
`

type CreateImportBatchStepParams struct {
	ID       uuid.UUID `json:"id"`
	BatchID  uuid.UUID `json:"batch_id"`
	StepType string    `json:"step_type"`
	JobID    uuid.UUID `json:"job_id"`
}

func (q *Queries) CreateImportBatchStep(ctx context.Context, arg CreateImportBatchStepParams) (FileImportBatchStep, error) {
	row := q.db.QueryRow(ctx, createImportBatchStep,
		arg.ID,
		arg.BatchID,
		arg.StepType,
		arg.JobID,
	)
	var i FileImportBatchStep
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StepType,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getFileObject = `-- name: GetFileObject :one
SELECT id, tenant_id, company_id, storage_provider, object_key, original_filename, detected_extension, detected_mime_type, size_bytes, sha256, encryption_mode, status, expires_at, legal_hold, created_by, created_at, updated_at FROM file.file_objects WHERE id = $1
`

func (q *Queries) GetFileObject(ctx context.Context, id uuid.UUID) (FileFileObject, error) {
	row := q.db.QueryRow(ctx, getFileObject, id)
	var i FileFileObject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.DetectedExtension,
		&i.DetectedMimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.EncryptionMode,
		&i.Status,
		&i.ExpiresAt,
		&i.LegalHold,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, tenant_id, company_id, operation, input_file_id, template_id, created_by, status, total_rows, valid_rows, invalid_rows, warning_rows, committed_rows, rejected_rows, validation_started_at, validation_finished_at, commit_started_at, commit_finished_at, expires_at, created_at, updated_at FROM file.import_batches WHERE id = $1
`

func (q *Queries) GetImportBatch(ctx context.Context, id uuid.UUID) (FileImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatch, id)
	var i FileImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Operation,
		&i.InputFileID,
		&i.TemplateID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.WarningRows,
		&i.CommittedRows,
		&i.RejectedRows,
		&i.ValidationStartedAt,
		&i.ValidationFinishedAt,
		&i.CommitStartedAt,
		&i.CommitFinishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBatchArtifacts = `-- name: ListBatchArtifacts :many
SELECT id, batch_id, file_object_id, role, created_at FROM file.batch_artifacts WHERE batch_id = $1 ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListBatchArtifacts(ctx context.Context, batchID uuid.UUID) ([]FileBatchArtifact, error) {
	rows, err := q.db.Query(ctx, listBatchArtifacts, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileBatchArtifact
	for rows.Next() {
		var i FileBatchArtifact
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.FileObjectID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportTemplates = `-- name: ListImportTemplates :many
SELECT id, template_type, version, file_format, status
FROM file.import_templates
WHERE status = 'active'
ORDER BY template_type ASC, version ASC, file_format ASC, id ASC
`

type ListImportTemplatesRow struct {
	ID           uuid.UUID `json:"id"`
	TemplateType string    `json:"template_type"`
	Version      string    `json:"version"`
	FileFormat   string    `json:"file_format"`
	Status       string    `json:"status"`
}

func (q *Queries) ListImportTemplates(ctx context.Context) ([]ListImportTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listImportTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportTemplatesRow
	for rows.Next() {
		var i ListImportTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateType,
			&i.Version,
			&i.FileFormat,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFileObjectAvailable = `-- name: MarkFileObjectAvailable :one
UPDATE file.file_objects
SET status = 'available', size_bytes = $1, sha256 = $2
WHERE id = $3 AND status = 'pending'
RETURNING id, tenant_id, company_id, storage_provider, object_key, original_filename, detected_extension, detected_mime_type, size_bytes, sha256, encryption_mode, status, expires_at, legal_hold, created_by, created_at, updated_at
`

type MarkFileObjectAvailableParams struct {
	SizeBytes int64     `json:"size_bytes"`
	Sha256    []byte    `json:"sha256"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) MarkFileObjectAvailable(ctx context.Context, arg MarkFileObjectAvailableParams) (FileFileObject, error) {
	row := q.db.QueryRow(ctx, markFileObjectAvailable, arg.SizeBytes, arg.Sha256, arg.ID)
	var i FileFileObject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.DetectedExtension,
		&i.DetectedMimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.EncryptionMode,
		&i.Status,
		&i.ExpiresAt,
		&i.LegalHold,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestImportBatchCommit = `-- name: RequestImportBatchCommit :one
UPDATE file.import_batches
SET status = 'commit_requested'
WHERE id = $1
  AND status = 'validated'
  AND invalid_rows = 0
RETURNING id, tenant_id, company_id, operation, input_file_id, template_id, created_by, status, total_rows, valid_rows, invalid_rows, warning_rows, committed_rows, rejected_rows, validation_started_at, validation_finished_at, commit_started_at, commit_finished_at, expires_at, created_at, updated_at
`

func (q *Queries) RequestImportBatchCommit(ctx context.Context, id uuid.UUID) (FileImportBatch, error) {
	row := q.db.QueryRow(ctx, requestImportBatchCommit, id)
	var i FileImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Operation,
		&i.InputFileID,
		&i.TemplateID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.WarningRows,
		&i.CommittedRows,
		&i.RejectedRows,
		&i.ValidationStartedAt,
		&i.ValidationFinishedAt,
		&i.CommitStartedAt,
		&i.CommitFinishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportBatchStatus = `-- name: UpdateImportBatchStatus :one
UPDATE file.import_batches
SET status = $1,
    validation_started_at = COALESCE($2, validation_started_at),
    validation_finished_at = COALESCE($3, validation_finished_at),
    commit_started_at = COALESCE($4, commit_started_at),
    commit_finished_at = COALESCE($5, commit_finished_at),
    total_rows = COALESCE($6, total_rows),
    valid_rows = COALESCE($7, valid_rows),
    invalid_rows = COALESCE($8, invalid_rows),
    warning_rows = COALESCE($9, warning_rows),
    committed_rows = COALESCE($10, committed_rows),
    rejected_rows = COALESCE($11, rejected_rows)
WHERE id = $12
RETURNING id, tenant_id, company_id, operation, input_file_id, template_id, created_by, status, total_rows, valid_rows, invalid_rows, warning_rows, committed_rows, rejected_rows, validation_started_at, validation_finished_at, commit_started_at, commit_finished_at, expires_at, created_at, updated_at
`

type UpdateImportBatchStatusParams struct {
	Status               string             `json:"status"`
	ValidationStartedAt  pgtype.Timestamptz `json:"validation_started_at"`
	ValidationFinishedAt pgtype.Timestamptz `json:"validation_finished_at"`
	CommitStartedAt      pgtype.Timestamptz `json:"commit_started_at"`
	CommitFinishedAt     pgtype.Timestamptz `json:"commit_finished_at"`
	TotalRows            *int32             `json:"total_rows"`
	ValidRows            *int32             `json:"valid_rows"`
	InvalidRows          *int32             `json:"invalid_rows"`
	WarningRows          *int32             `json:"warning_rows"`
	CommittedRows        *int32             `json:"committed_rows"`
	RejectedRows         *int32             `json:"rejected_rows"`
	ID                   uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateImportBatchStatus(ctx context.Context, arg UpdateImportBatchStatusParams) (FileImportBatch, error) {
	row := q.db.QueryRow(ctx, updateImportBatchStatus,
		arg.Status,
		arg.ValidationStartedAt,
		arg.ValidationFinishedAt,
		arg.CommitStartedAt,
		arg.CommitFinishedAt,
		arg.TotalRows,
		arg.ValidRows,
		arg.InvalidRows,
		arg.WarningRows,
		arg.CommittedRows,
		arg.RejectedRows,
		arg.ID,
	)
	var i FileImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Operation,
		&i.InputFileID,
		&i.TemplateID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.WarningRows,
		&i.CommittedRows,
		&i.RejectedRows,
		&i.ValidationStartedAt,
		&i.ValidationFinishedAt,
		&i.CommitStartedAt,
		&i.CommitFinishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportBatchStepStatus = `-- name: UpdateImportBatchStepStatus :one
UPDATE file.import_batch_steps
SET status = $1,
    started_at = COALESCE($2, started_at),
    finished_at = COALESCE($3, finished_at)
WHERE id = $4
RETURNING id, batch_id, step_type, job_id, status, created_at, started_at, finished_at
`

type UpdateImportBatchStepStatusParams struct {
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateImportBatchStepStatus(ctx context.Context, arg UpdateImportBatchStepStatusParams) (FileImportBatchStep, error) {
	row := q.db.QueryRow(ctx, updateImportBatchStepStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i FileImportBatchStep
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StepType,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
