// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: file_batches.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBackgroundJobsForBatch = `-- name: CancelBackgroundJobsForBatch :exec
UPDATE platform.background_jobs AS job
SET status = CASE
        WHEN job.status IN ('queued', 'retry_scheduled') THEN 'canceled'
        ELSE 'cancel_requested'
    END,
    completed_at = CASE
        WHEN job.status IN ('queued', 'retry_scheduled') THEN clock_timestamp()
        ELSE job.completed_at
    END
FROM file.import_batch_steps AS step
WHERE step.batch_id = $1
  AND step.job_id = job.id
  AND job.status IN ('queued', 'retry_scheduled', 'running')
`

func (q *Queries) CancelBackgroundJobsForBatch(ctx context.Context, batchID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelBackgroundJobsForBatch, batchID)
	return err
}

const clearImportBatchValidationRows = `-- name: ClearImportBatchValidationRows :exec
DELETE FROM file.import_batch_rows
WHERE batch_id = $1
`

func (q *Queries) ClearImportBatchValidationRows(ctx context.Context, batchID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearImportBatchValidationRows, batchID)
	return err
}

const createBatchArtifact = `-- name: CreateBatchArtifact :one
INSERT INTO file.batch_artifacts (id, batch_id, file_object_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (batch_id, role) DO UPDATE
SET file_object_id = EXCLUDED.file_object_id
RETURNING id, batch_id, file_object_id, role, created_at
`

type CreateBatchArtifactParams struct {
	ID           uuid.UUID `json:"id"`
	BatchID      uuid.UUID `json:"batch_id"`
	FileObjectID uuid.UUID `json:"file_object_id"`
	Role         string    `json:"role"`
}

func (q *Queries) CreateBatchArtifact(ctx context.Context, arg CreateBatchArtifactParams) (FileBatchArtifact, error) {
	row := q.db.QueryRow(ctx, createBatchArtifact,
		arg.ID,
		arg.BatchID,
		arg.FileObjectID,
		arg.Role,
	)
	var i FileBatchArtifact
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.FileObjectID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createFileObject = `-- name: CreateFileObject :one
INSERT INTO file.file_objects (
    id, tenant_id, company_id, storage_provider, object_key, original_filename,
    detected_extension, detected_mime_type, size_bytes, sha256, encryption_mode,
    status, expires_at, created_by
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14
)
RETURNING id, tenant_id, company_id, storage_provider, object_key, original_filename, detected_extension, detected_mime_type, size_bytes, sha256, encryption_mode, status, expires_at, legal_hold, created_by, created_at, updated_at
`

type CreateFileObjectParams struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          *uuid.UUID         `json:"tenant_id"`
	CompanyID         *uuid.UUID         `json:"company_id"`
	StorageProvider   string             `json:"storage_provider"`
	ObjectKey         string             `json:"object_key"`
	OriginalFilename  string             `json:"original_filename"`
	DetectedExtension string             `json:"detected_extension"`
	DetectedMimeType  string             `json:"detected_mime_type"`
	SizeBytes         int64              `json:"size_bytes"`
	Sha256            []byte             `json:"sha256"`
	EncryptionMode    string             `json:"encryption_mode"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedBy         *uuid.UUID         `json:"created_by"`
}

func (q *Queries) CreateFileObject(ctx context.Context, arg CreateFileObjectParams) (FileFileObject, error) {
	row := q.db.QueryRow(ctx, createFileObject,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.StorageProvider,
		arg.ObjectKey,
		arg.OriginalFilename,
		arg.DetectedExtension,
		arg.DetectedMimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.EncryptionMode,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i FileFileObject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.DetectedExtension,
		&i.DetectedMimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.EncryptionMode,
		&i.Status,
		&i.ExpiresAt,
		&i.LegalHold,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO file.import_batches (
    id, tenant_id, company_id, operation, input_file_id, template_id, created_by, expires_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, tenant_id, company_id, operation, input_file_id, template_id, created_by, status, total_rows, valid_rows, invalid_rows, warning_rows, committed_rows, rejected_rows, validation_started_at, validation_finished_at, commit_started_at, commit_finished_at, expires_at, created_at, updated_at
`

type CreateImportBatchParams struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	Operation   string             `json:"operation"`
	InputFileID uuid.UUID          `json:"input_file_id"`
	TemplateID  *uuid.UUID         `json:"template_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (FileImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.Operation,
		arg.InputFileID,
		arg.TemplateID,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i FileImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Operation,
		&i.InputFileID,
		&i.TemplateID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.WarningRows,
		&i.CommittedRows,
		&i.RejectedRows,
		&i.ValidationStartedAt,
		&i.ValidationFinishedAt,
		&i.CommitStartedAt,
		&i.CommitFinishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportBatchPayrollContext = `-- name: CreateImportBatchPayrollContext :one
INSERT INTO file.import_batch_payroll_context (
    batch_id, tenant_id, company_id, tax_year, tax_month, coverage_from,
    coverage_to, pay_date, run_type, correction_of_run_id
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10
)
RETURNING batch_id, tenant_id, company_id, tax_year, tax_month, coverage_from, coverage_to, pay_date, run_type, payroll_period_id, payroll_run_id, created_at, updated_at, correction_of_run_id
`

type CreateImportBatchPayrollContextParams struct {
	BatchID           uuid.UUID   `json:"batch_id"`
	TenantID          uuid.UUID   `json:"tenant_id"`
	CompanyID         uuid.UUID   `json:"company_id"`
	TaxYear           int32       `json:"tax_year"`
	TaxMonth          int32       `json:"tax_month"`
	CoverageFrom      pgtype.Date `json:"coverage_from"`
	CoverageTo        pgtype.Date `json:"coverage_to"`
	PayDate           pgtype.Date `json:"pay_date"`
	RunType           string      `json:"run_type"`
	CorrectionOfRunID *uuid.UUID  `json:"correction_of_run_id"`
}

func (q *Queries) CreateImportBatchPayrollContext(ctx context.Context, arg CreateImportBatchPayrollContextParams) (FileImportBatchPayrollContext, error) {
	row := q.db.QueryRow(ctx, createImportBatchPayrollContext,
		arg.BatchID,
		arg.TenantID,
		arg.CompanyID,
		arg.TaxYear,
		arg.TaxMonth,
		arg.CoverageFrom,
		arg.CoverageTo,
		arg.PayDate,
		arg.RunType,
		arg.CorrectionOfRunID,
	)
	var i FileImportBatchPayrollContext
	err := row.Scan(
		&i.BatchID,
		&i.TenantID,
		&i.CompanyID,
		&i.TaxYear,
		&i.TaxMonth,
		&i.CoverageFrom,
		&i.CoverageTo,
		&i.PayDate,
		&i.RunType,
		&i.PayrollPeriodID,
		&i.PayrollRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CorrectionOfRunID,
	)
	return i, err
}

const createImportBatchRow = `-- name: CreateImportBatchRow :one
INSERT INTO file.import_batch_rows (
    id, batch_id, sheet_name, row_no, source_employee_number,
    source_full_name, match_status, normalized_payload, issue_count,
    blocking_issue_count, employee_id, employment_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9,
    $10, $11, $12
)
RETURNING id, batch_id, sheet_name, row_no, source_employee_number, source_full_name, match_status, employee_id, employment_id, normalized_payload, issue_count, blocking_issue_count, created_at, updated_at
`

type CreateImportBatchRowParams struct {
	ID                   uuid.UUID  `json:"id"`
	BatchID              uuid.UUID  `json:"batch_id"`
	SheetName            string     `json:"sheet_name"`
	RowNo                int32      `json:"row_no"`
	SourceEmployeeNumber *string    `json:"source_employee_number"`
	SourceFullName       *string    `json:"source_full_name"`
	MatchStatus          string     `json:"match_status"`
	NormalizedPayload    []byte     `json:"normalized_payload"`
	IssueCount           int32      `json:"issue_count"`
	BlockingIssueCount   int32      `json:"blocking_issue_count"`
	EmployeeID           *uuid.UUID `json:"employee_id"`
	EmploymentID         *uuid.UUID `json:"employment_id"`
}

func (q *Queries) CreateImportBatchRow(ctx context.Context, arg CreateImportBatchRowParams) (FileImportBatchRow, error) {
	row := q.db.QueryRow(ctx, createImportBatchRow,
		arg.ID,
		arg.BatchID,
		arg.SheetName,
		arg.RowNo,
		arg.SourceEmployeeNumber,
		arg.SourceFullName,
		arg.MatchStatus,
		arg.NormalizedPayload,
		arg.IssueCount,
		arg.BlockingIssueCount,
		arg.EmployeeID,
		arg.EmploymentID,
	)
	var i FileImportBatchRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.SheetName,
		&i.RowNo,
		&i.SourceEmployeeNumber,
		&i.SourceFullName,
		&i.MatchStatus,
		&i.EmployeeID,
		&i.EmploymentID,
		&i.NormalizedPayload,
		&i.IssueCount,
		&i.BlockingIssueCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportBatchStep = `-- name: CreateImportBatchStep :one
INSERT INTO file.import_batch_steps (id, batch_id, step_type, job_id)
VALUES ($1, $2, $3, $4)
RETURNING id, batch_id, step_type, job_id, status, created_at, started_at, finished_at
`

type CreateImportBatchStepParams struct {
	ID       uuid.UUID `json:"id"`
	BatchID  uuid.UUID `json:"batch_id"`
	StepType string    `json:"step_type"`
	JobID    uuid.UUID `json:"job_id"`
}

func (q *Queries) CreateImportBatchStep(ctx context.Context, arg CreateImportBatchStepParams) (FileImportBatchStep, error) {
	row := q.db.QueryRow(ctx, createImportBatchStep,
		arg.ID,
		arg.BatchID,
		arg.StepType,
		arg.JobID,
	)
	var i FileImportBatchStep
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StepType,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createImportRowDecision = `-- name: CreateImportRowDecision :one
INSERT INTO file.import_row_decisions (
    id, row_id, employee_id, employment_id, decision, reason, decided_by
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, row_id, employee_id, employment_id, decision, reason, decided_by, decided_at
`

type CreateImportRowDecisionParams struct {
	ID           uuid.UUID  `json:"id"`
	RowID        uuid.UUID  `json:"row_id"`
	EmployeeID   *uuid.UUID `json:"employee_id"`
	EmploymentID *uuid.UUID `json:"employment_id"`
	Decision     string     `json:"decision"`
	Reason       string     `json:"reason"`
	DecidedBy    uuid.UUID  `json:"decided_by"`
}

func (q *Queries) CreateImportRowDecision(ctx context.Context, arg CreateImportRowDecisionParams) (FileImportRowDecision, error) {
	row := q.db.QueryRow(ctx, createImportRowDecision,
		arg.ID,
		arg.RowID,
		arg.EmployeeID,
		arg.EmploymentID,
		arg.Decision,
		arg.Reason,
		arg.DecidedBy,
	)
	var i FileImportRowDecision
	err := row.Scan(
		&i.ID,
		&i.RowID,
		&i.EmployeeID,
		&i.EmploymentID,
		&i.Decision,
		&i.Reason,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const createImportRowEffect = `-- name: CreateImportRowEffect :one
INSERT INTO file.import_row_effects (id, batch_id, row_id, entity_type, entity_id, action)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (batch_id, row_id, entity_type, entity_id, action) DO UPDATE SET created_at = file.import_row_effects.created_at
RETURNING id, batch_id, row_id, entity_type, entity_id, action, created_at
`

type CreateImportRowEffectParams struct {
	ID         uuid.UUID `json:"id"`
	BatchID    uuid.UUID `json:"batch_id"`
	RowID      uuid.UUID `json:"row_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Action     string    `json:"action"`
}

func (q *Queries) CreateImportRowEffect(ctx context.Context, arg CreateImportRowEffectParams) (FileImportRowEffect, error) {
	row := q.db.QueryRow(ctx, createImportRowEffect,
		arg.ID,
		arg.BatchID,
		arg.RowID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
	)
	var i FileImportRowEffect
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.RowID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const createImportRowIssue = `-- name: CreateImportRowIssue :one
INSERT INTO file.import_row_issues (
    id, row_id, batch_id, sheet_name, row_no, field_name, error_code,
    severity, description, masked_value, candidate_count, details
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12
)
RETURNING id, row_id, batch_id, sheet_name, row_no, field_name, error_code, severity, description, masked_value, candidate_count, details, created_at
`

type CreateImportRowIssueParams struct {
	ID             uuid.UUID `json:"id"`
	RowID          uuid.UUID `json:"row_id"`
	BatchID        uuid.UUID `json:"batch_id"`
	SheetName      string    `json:"sheet_name"`
	RowNo          int32     `json:"row_no"`
	FieldName      *string   `json:"field_name"`
	ErrorCode      string    `json:"error_code"`
	Severity       string    `json:"severity"`
	Description    string    `json:"description"`
	MaskedValue    *string   `json:"masked_value"`
	CandidateCount int32     `json:"candidate_count"`
	Details        []byte    `json:"details"`
}

func (q *Queries) CreateImportRowIssue(ctx context.Context, arg CreateImportRowIssueParams) (FileImportRowIssue, error) {
	row := q.db.QueryRow(ctx, createImportRowIssue,
		arg.ID,
		arg.RowID,
		arg.BatchID,
		arg.SheetName,
		arg.RowNo,
		arg.FieldName,
		arg.ErrorCode,
		arg.Severity,
		arg.Description,
		arg.MaskedValue,
		arg.CandidateCount,
		arg.Details,
	)
	var i FileImportRowIssue
	err := row.Scan(
		&i.ID,
		&i.RowID,
		&i.BatchID,
		&i.SheetName,
		&i.RowNo,
		&i.FieldName,
		&i.ErrorCode,
		&i.Severity,
		&i.Description,
		&i.MaskedValue,
		&i.CandidateCount,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const createImportTemplate = `-- name: CreateImportTemplate :one
INSERT INTO file.import_templates (
    id, tenant_id, company_id, template_type, version, file_format, configuration, status
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, 'active'
)
RETURNING id, template_type, version, file_format, artifact_id, schema, status, created_at, tenant_id, company_id, configuration, effective_from, effective_to
`

type CreateImportTemplateParams struct {
	ID            uuid.UUID  `json:"id"`
	TenantID      *uuid.UUID `json:"tenant_id"`
	CompanyID     *uuid.UUID `json:"company_id"`
	TemplateType  string     `json:"template_type"`
	Version       string     `json:"version"`
	FileFormat    string     `json:"file_format"`
	Configuration []byte     `json:"configuration"`
}

func (q *Queries) CreateImportTemplate(ctx context.Context, arg CreateImportTemplateParams) (FileImportTemplate, error) {
	row := q.db.QueryRow(ctx, createImportTemplate,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.TemplateType,
		arg.Version,
		arg.FileFormat,
		arg.Configuration,
	)
	var i FileImportTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateType,
		&i.Version,
		&i.FileFormat,
		&i.ArtifactID,
		&i.Schema,
		&i.Status,
		&i.CreatedAt,
		&i.TenantID,
		&i.CompanyID,
		&i.Configuration,
		&i.EffectiveFrom,
		&i.EffectiveTo,
	)
	return i, err
}

const getFileObject = `-- name: GetFileObject :one
SELECT id, tenant_id, company_id, storage_provider, object_key, original_filename, detected_extension, detected_mime_type, size_bytes, sha256, encryption_mode, status, expires_at, legal_hold, created_by, created_at, updated_at FROM file.file_objects WHERE id = $1
`

func (q *Queries) GetFileObject(ctx context.Context, id uuid.UUID) (FileFileObject, error) {
	row := q.db.QueryRow(ctx, getFileObject, id)
	var i FileFileObject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.DetectedExtension,
		&i.DetectedMimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.EncryptionMode,
		&i.Status,
		&i.ExpiresAt,
		&i.LegalHold,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, tenant_id, company_id, operation, input_file_id, template_id, created_by, status, total_rows, valid_rows, invalid_rows, warning_rows, committed_rows, rejected_rows, validation_started_at, validation_finished_at, commit_started_at, commit_finished_at, expires_at, created_at, updated_at FROM file.import_batches WHERE id = $1
`

func (q *Queries) GetImportBatch(ctx context.Context, id uuid.UUID) (FileImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatch, id)
	var i FileImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Operation,
		&i.InputFileID,
		&i.TemplateID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.WarningRows,
		&i.CommittedRows,
		&i.RejectedRows,
		&i.ValidationStartedAt,
		&i.ValidationFinishedAt,
		&i.CommitStartedAt,
		&i.CommitFinishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportBatchPayrollContext = `-- name: GetImportBatchPayrollContext :one
SELECT batch_id, tenant_id, company_id, tax_year, tax_month, coverage_from, coverage_to, pay_date, run_type, payroll_period_id, payroll_run_id, created_at, updated_at, correction_of_run_id FROM file.import_batch_payroll_context WHERE batch_id = $1
`

func (q *Queries) GetImportBatchPayrollContext(ctx context.Context, batchID uuid.UUID) (FileImportBatchPayrollContext, error) {
	row := q.db.QueryRow(ctx, getImportBatchPayrollContext, batchID)
	var i FileImportBatchPayrollContext
	err := row.Scan(
		&i.BatchID,
		&i.TenantID,
		&i.CompanyID,
		&i.TaxYear,
		&i.TaxMonth,
		&i.CoverageFrom,
		&i.CoverageTo,
		&i.PayDate,
		&i.RunType,
		&i.PayrollPeriodID,
		&i.PayrollRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CorrectionOfRunID,
	)
	return i, err
}

const getImportTemplate = `-- name: GetImportTemplate :one
SELECT id, template_type, version, file_format, artifact_id, schema, status, created_at, tenant_id, company_id, configuration, effective_from, effective_to
FROM file.import_templates
WHERE id = $1
`

func (q *Queries) GetImportTemplate(ctx context.Context, id uuid.UUID) (FileImportTemplate, error) {
	row := q.db.QueryRow(ctx, getImportTemplate, id)
	var i FileImportTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateType,
		&i.Version,
		&i.FileFormat,
		&i.ArtifactID,
		&i.Schema,
		&i.Status,
		&i.CreatedAt,
		&i.TenantID,
		&i.CompanyID,
		&i.Configuration,
		&i.EffectiveFrom,
		&i.EffectiveTo,
	)
	return i, err
}

const linkImportBatchPayrollContext = `-- name: LinkImportBatchPayrollContext :one
UPDATE file.import_batch_payroll_context
SET payroll_period_id = $1,
    payroll_run_id = $2,
    updated_at = clock_timestamp()
WHERE batch_id = $3
RETURNING batch_id, tenant_id, company_id, tax_year, tax_month, coverage_from, coverage_to, pay_date, run_type, payroll_period_id, payroll_run_id, created_at, updated_at, correction_of_run_id
`

type LinkImportBatchPayrollContextParams struct {
	PayrollPeriodID *uuid.UUID `json:"payroll_period_id"`
	PayrollRunID    *uuid.UUID `json:"payroll_run_id"`
	BatchID         uuid.UUID  `json:"batch_id"`
}

func (q *Queries) LinkImportBatchPayrollContext(ctx context.Context, arg LinkImportBatchPayrollContextParams) (FileImportBatchPayrollContext, error) {
	row := q.db.QueryRow(ctx, linkImportBatchPayrollContext, arg.PayrollPeriodID, arg.PayrollRunID, arg.BatchID)
	var i FileImportBatchPayrollContext
	err := row.Scan(
		&i.BatchID,
		&i.TenantID,
		&i.CompanyID,
		&i.TaxYear,
		&i.TaxMonth,
		&i.CoverageFrom,
		&i.CoverageTo,
		&i.PayDate,
		&i.RunType,
		&i.PayrollPeriodID,
		&i.PayrollRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CorrectionOfRunID,
	)
	return i, err
}

const listBatchArtifacts = `-- name: ListBatchArtifacts :many
SELECT id, batch_id, file_object_id, role, created_at FROM file.batch_artifacts WHERE batch_id = $1 ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListBatchArtifacts(ctx context.Context, batchID uuid.UUID) ([]FileBatchArtifact, error) {
	rows, err := q.db.Query(ctx, listBatchArtifacts, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileBatchArtifact
	for rows.Next() {
		var i FileBatchArtifact
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.FileObjectID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportBatchRows = `-- name: ListImportBatchRows :many
SELECT id, batch_id, sheet_name, row_no, source_employee_number, source_full_name, match_status, employee_id, employment_id, normalized_payload, issue_count, blocking_issue_count, created_at, updated_at
FROM file.import_batch_rows
WHERE batch_id = $1
ORDER BY sheet_name ASC, row_no ASC
`

func (q *Queries) ListImportBatchRows(ctx context.Context, batchID uuid.UUID) ([]FileImportBatchRow, error) {
	rows, err := q.db.Query(ctx, listImportBatchRows, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileImportBatchRow
	for rows.Next() {
		var i FileImportBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.SheetName,
			&i.RowNo,
			&i.SourceEmployeeNumber,
			&i.SourceFullName,
			&i.MatchStatus,
			&i.EmployeeID,
			&i.EmploymentID,
			&i.NormalizedPayload,
			&i.IssueCount,
			&i.BlockingIssueCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportTemplates = `-- name: ListImportTemplates :many
SELECT id, tenant_id, company_id, template_type, version, file_format, status
FROM file.import_templates
WHERE status = 'active'
  AND (tenant_id IS NULL OR tenant_id = $1)
ORDER BY template_type ASC, version ASC, file_format ASC, id ASC
`

type ListImportTemplatesRow struct {
	ID           uuid.UUID  `json:"id"`
	TenantID     *uuid.UUID `json:"tenant_id"`
	CompanyID    *uuid.UUID `json:"company_id"`
	TemplateType string     `json:"template_type"`
	Version      string     `json:"version"`
	FileFormat   string     `json:"file_format"`
	Status       string     `json:"status"`
}

func (q *Queries) ListImportTemplates(ctx context.Context, tenantID *uuid.UUID) ([]ListImportTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listImportTemplates, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportTemplatesRow
	for rows.Next() {
		var i ListImportTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyID,
			&i.TemplateType,
			&i.Version,
			&i.FileFormat,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportValidationIssues = `-- name: ListImportValidationIssues :many
SELECT id, row_id, sheet_name, row_no, field_name, error_code, severity,
       description, masked_value, candidate_count
FROM file.import_row_issues
WHERE batch_id = $1
ORDER BY sheet_name ASC, row_no ASC, id ASC
`

type ListImportValidationIssuesRow struct {
	ID             uuid.UUID `json:"id"`
	RowID          uuid.UUID `json:"row_id"`
	SheetName      string    `json:"sheet_name"`
	RowNo          int32     `json:"row_no"`
	FieldName      *string   `json:"field_name"`
	ErrorCode      string    `json:"error_code"`
	Severity       string    `json:"severity"`
	Description    string    `json:"description"`
	MaskedValue    *string   `json:"masked_value"`
	CandidateCount int32     `json:"candidate_count"`
}

func (q *Queries) ListImportValidationIssues(ctx context.Context, batchID uuid.UUID) ([]ListImportValidationIssuesRow, error) {
	rows, err := q.db.Query(ctx, listImportValidationIssues, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportValidationIssuesRow
	for rows.Next() {
		var i ListImportValidationIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.RowID,
			&i.SheetName,
			&i.RowNo,
			&i.FieldName,
			&i.ErrorCode,
			&i.Severity,
			&i.Description,
			&i.MaskedValue,
			&i.CandidateCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportValidationSheets = `-- name: ListImportValidationSheets :many
SELECT
    sheet_name,
    count(*)::bigint AS total_rows,
    count(*) FILTER (WHERE blocking_issue_count = 0)::bigint AS valid_rows,
    count(*) FILTER (WHERE blocking_issue_count > 0)::bigint AS invalid_rows,
    count(*) FILTER (WHERE blocking_issue_count > 0)::bigint AS blocking_rows
FROM file.import_batch_rows
WHERE batch_id = $1
GROUP BY sheet_name
ORDER BY sheet_name ASC
`

type ListImportValidationSheetsRow struct {
	SheetName    string `json:"sheet_name"`
	TotalRows    int64  `json:"total_rows"`
	ValidRows    int64  `json:"valid_rows"`
	InvalidRows  int64  `json:"invalid_rows"`
	BlockingRows int64  `json:"blocking_rows"`
}

func (q *Queries) ListImportValidationSheets(ctx context.Context, batchID uuid.UUID) ([]ListImportValidationSheetsRow, error) {
	rows, err := q.db.Query(ctx, listImportValidationSheets, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportValidationSheetsRow
	for rows.Next() {
		var i ListImportValidationSheetsRow
		if err := rows.Scan(
			&i.SheetName,
			&i.TotalRows,
			&i.ValidRows,
			&i.InvalidRows,
			&i.BlockingRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFileObjectAvailable = `-- name: MarkFileObjectAvailable :one
UPDATE file.file_objects
SET status = 'available', size_bytes = $1, sha256 = $2
WHERE id = $3 AND status = 'pending'
RETURNING id, tenant_id, company_id, storage_provider, object_key, original_filename, detected_extension, detected_mime_type, size_bytes, sha256, encryption_mode, status, expires_at, legal_hold, created_by, created_at, updated_at
`

type MarkFileObjectAvailableParams struct {
	SizeBytes int64     `json:"size_bytes"`
	Sha256    []byte    `json:"sha256"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) MarkFileObjectAvailable(ctx context.Context, arg MarkFileObjectAvailableParams) (FileFileObject, error) {
	row := q.db.QueryRow(ctx, markFileObjectAvailable, arg.SizeBytes, arg.Sha256, arg.ID)
	var i FileFileObject
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.OriginalFilename,
		&i.DetectedExtension,
		&i.DetectedMimeType,
		&i.SizeBytes,
		&i.Sha256,
		&i.EncryptionMode,
		&i.Status,
		&i.ExpiresAt,
		&i.LegalHold,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestImportBatchCommit = `-- name: RequestImportBatchCommit :one
UPDATE file.import_batches
SET status = 'commit_requested'
WHERE id = $1
  AND status = 'validated'
  AND invalid_rows = 0
RETURNING id, tenant_id, company_id, operation, input_file_id, template_id, created_by, status, total_rows, valid_rows, invalid_rows, warning_rows, committed_rows, rejected_rows, validation_started_at, validation_finished_at, commit_started_at, commit_finished_at, expires_at, created_at, updated_at
`

func (q *Queries) RequestImportBatchCommit(ctx context.Context, id uuid.UUID) (FileImportBatch, error) {
	row := q.db.QueryRow(ctx, requestImportBatchCommit, id)
	var i FileImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Operation,
		&i.InputFileID,
		&i.TemplateID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.WarningRows,
		&i.CommittedRows,
		&i.RejectedRows,
		&i.ValidationStartedAt,
		&i.ValidationFinishedAt,
		&i.CommitStartedAt,
		&i.CommitFinishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveImportBatchRow = `-- name: ResolveImportBatchRow :one
WITH selected_batch AS (
    SELECT tenant_id, company_id
    FROM file.import_batches
    WHERE id = $1
), updated_row AS (
    UPDATE file.import_batch_rows row
    SET match_status = 'resolved',
        employee_id = $2,
        employment_id = $3,
        blocking_issue_count = 0,
        updated_at = clock_timestamp()
    WHERE row.id = $4
      AND row.batch_id = $1
      AND (
          $2::platform.uuid_v7 IS NULL
          OR EXISTS (
              SELECT 1
              FROM employee.employees employee
              JOIN selected_batch batch ON batch.tenant_id = employee.tenant_id AND batch.company_id = employee.company_id
              WHERE employee.id = $2::platform.uuid_v7
          )
      )
    RETURNING row.batch_id
)
UPDATE file.import_batches batch
SET total_rows = counts.total_rows,
    valid_rows = counts.valid_rows,
    invalid_rows = counts.invalid_rows,
    status = CASE WHEN counts.invalid_rows = 0 THEN 'validated' ELSE 'validation_failed' END,
    updated_at = clock_timestamp()
FROM (
    SELECT rows.batch_id,
           count(*)::integer AS total_rows,
           count(*) FILTER (WHERE blocking_issue_count = 0)::integer AS valid_rows,
           count(*) FILTER (WHERE blocking_issue_count > 0)::integer AS invalid_rows
    FROM file.import_batch_rows rows
    WHERE rows.batch_id = $1
    GROUP BY rows.batch_id
) counts
WHERE batch.id = counts.batch_id
  AND batch.id IN (SELECT batch_id FROM updated_row)
RETURNING batch.id
`

type ResolveImportBatchRowParams struct {
	BatchID      uuid.UUID  `json:"batch_id"`
	EmployeeID   *uuid.UUID `json:"employee_id"`
	EmploymentID *uuid.UUID `json:"employment_id"`
	RowID        uuid.UUID  `json:"row_id"`
}

func (q *Queries) ResolveImportBatchRow(ctx context.Context, arg ResolveImportBatchRowParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveImportBatchRow,
		arg.BatchID,
		arg.EmployeeID,
		arg.EmploymentID,
		arg.RowID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const retireImportTemplate = `-- name: RetireImportTemplate :one
UPDATE file.import_templates
SET status = 'retired'
WHERE id = $1 AND status = 'active'
RETURNING id, template_type, version, file_format, artifact_id, schema, status, created_at, tenant_id, company_id, configuration, effective_from, effective_to
`

func (q *Queries) RetireImportTemplate(ctx context.Context, id uuid.UUID) (FileImportTemplate, error) {
	row := q.db.QueryRow(ctx, retireImportTemplate, id)
	var i FileImportTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateType,
		&i.Version,
		&i.FileFormat,
		&i.ArtifactID,
		&i.Schema,
		&i.Status,
		&i.CreatedAt,
		&i.TenantID,
		&i.CompanyID,
		&i.Configuration,
		&i.EffectiveFrom,
		&i.EffectiveTo,
	)
	return i, err
}

const updateImportBatchStatus = `-- name: UpdateImportBatchStatus :one
UPDATE file.import_batches
SET status = $1,
    validation_started_at = COALESCE($2, validation_started_at),
    validation_finished_at = COALESCE($3, validation_finished_at),
    commit_started_at = COALESCE($4, commit_started_at),
    commit_finished_at = COALESCE($5, commit_finished_at),
    total_rows = COALESCE($6, total_rows),
    valid_rows = COALESCE($7, valid_rows),
    invalid_rows = COALESCE($8, invalid_rows),
    warning_rows = COALESCE($9, warning_rows),
    committed_rows = COALESCE($10, committed_rows),
    rejected_rows = COALESCE($11, rejected_rows)
WHERE id = $12
RETURNING id, tenant_id, company_id, operation, input_file_id, template_id, created_by, status, total_rows, valid_rows, invalid_rows, warning_rows, committed_rows, rejected_rows, validation_started_at, validation_finished_at, commit_started_at, commit_finished_at, expires_at, created_at, updated_at
`

type UpdateImportBatchStatusParams struct {
	Status               string             `json:"status"`
	ValidationStartedAt  pgtype.Timestamptz `json:"validation_started_at"`
	ValidationFinishedAt pgtype.Timestamptz `json:"validation_finished_at"`
	CommitStartedAt      pgtype.Timestamptz `json:"commit_started_at"`
	CommitFinishedAt     pgtype.Timestamptz `json:"commit_finished_at"`
	TotalRows            *int32             `json:"total_rows"`
	ValidRows            *int32             `json:"valid_rows"`
	InvalidRows          *int32             `json:"invalid_rows"`
	WarningRows          *int32             `json:"warning_rows"`
	CommittedRows        *int32             `json:"committed_rows"`
	RejectedRows         *int32             `json:"rejected_rows"`
	ID                   uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateImportBatchStatus(ctx context.Context, arg UpdateImportBatchStatusParams) (FileImportBatch, error) {
	row := q.db.QueryRow(ctx, updateImportBatchStatus,
		arg.Status,
		arg.ValidationStartedAt,
		arg.ValidationFinishedAt,
		arg.CommitStartedAt,
		arg.CommitFinishedAt,
		arg.TotalRows,
		arg.ValidRows,
		arg.InvalidRows,
		arg.WarningRows,
		arg.CommittedRows,
		arg.RejectedRows,
		arg.ID,
	)
	var i FileImportBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Operation,
		&i.InputFileID,
		&i.TemplateID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRows,
		&i.ValidRows,
		&i.InvalidRows,
		&i.WarningRows,
		&i.CommittedRows,
		&i.RejectedRows,
		&i.ValidationStartedAt,
		&i.ValidationFinishedAt,
		&i.CommitStartedAt,
		&i.CommitFinishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateImportBatchStepStatus = `-- name: UpdateImportBatchStepStatus :one
UPDATE file.import_batch_steps
SET status = $1,
    started_at = COALESCE($2, started_at),
    finished_at = COALESCE($3, finished_at)
WHERE id = $4
RETURNING id, batch_id, step_type, job_id, status, created_at, started_at, finished_at
`

type UpdateImportBatchStepStatusParams struct {
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateImportBatchStepStatus(ctx context.Context, arg UpdateImportBatchStepStatusParams) (FileImportBatchStep, error) {
	row := q.db.QueryRow(ctx, updateImportBatchStepStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i FileImportBatchStep
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StepType,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
