// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockPlatformUser = `-- name: BlockPlatformUser :one
UPDATE platform.users
SET status = 'blocked'
WHERE id = $1
RETURNING id, google_subject, email, display_name, status, created_at, updated_at
`

func (q *Queries) BlockPlatformUser(ctx context.Context, id uuid.UUID) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, blockPlatformUser, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPendingPlatformUser = `-- name: CreatePendingPlatformUser :one
INSERT INTO platform.users (
    id,
    email,
    display_name,
    status
)
VALUES (
    $1,
    lower($2),
    $3,
    'pending'
)
RETURNING id, google_subject, email, display_name, status, created_at, updated_at
`

type CreatePendingPlatformUserParams struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreatePendingPlatformUser(ctx context.Context, arg CreatePendingPlatformUserParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, createPendingPlatformUser, arg.ID, arg.Email, arg.DisplayName)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO platform.sessions (
    id,
    user_id,
    token_hash,
    created_at,
    expires_at,
    last_seen_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
`

type CreateSessionParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
	)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const createTenantMembership = `-- name: CreateTenantMembership :one
INSERT INTO platform.tenant_memberships (
    id,
    user_id,
    tenant_id,
    role_code
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (user_id, tenant_id)
DO UPDATE SET
    role_code = EXCLUDED.role_code,
    status = 'active'
RETURNING id, user_id, tenant_id, role_code, status, created_at, updated_at
`

type CreateTenantMembershipParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	RoleCode string    `json:"role_code"`
}

func (q *Queries) CreateTenantMembership(ctx context.Context, arg CreateTenantMembershipParams) (PlatformTenantMembership, error) {
	row := q.db.QueryRow(ctx, createTenantMembership,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.RoleCode,
	)
	var i PlatformTenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
FROM platform.sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > clock_timestamp()
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPlatformAdmin = `-- name: GetPlatformAdmin :one
SELECT u.id, u.google_subject, u.email, u.display_name, u.status, u.created_at, u.updated_at
FROM platform.platform_admins a
JOIN platform.users u ON u.id = a.user_id
WHERE a.user_id = $1
  AND u.status = 'active'
`

func (q *Queries) GetPlatformAdmin(ctx context.Context, userID uuid.UUID) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformAdmin, userID)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformUser = `-- name: GetPlatformUser :one
SELECT id, google_subject, email, display_name, status, created_at, updated_at
FROM platform.users
WHERE id = $1
`

func (q *Queries) GetPlatformUser(ctx context.Context, id uuid.UUID) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformUser, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformUserByID = `-- name: GetPlatformUserByID :one
SELECT id, google_subject, email, display_name, status, created_at, updated_at
FROM platform.users
WHERE id = $1
`

func (q *Queries) GetPlatformUserByID(ctx context.Context, id uuid.UUID) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformUserByID, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantMembership = `-- name: GetTenantMembership :one
SELECT
    tm.id AS membership_id,
    tm.user_id,
    tm.tenant_id,
    tm.role_code,
    tm.status AS membership_status,
    tm.created_at AS membership_created_at,
    tm.updated_at AS membership_updated_at,
    u.email AS user_email,
    u.display_name AS user_display_name,
    u.status AS user_status,
    CASE WHEN u.google_subject IS NULL THEN false ELSE true END AS user_google_linked
FROM platform.tenant_memberships tm
JOIN platform.users u ON u.id = tm.user_id
WHERE tm.id = $1
`

type GetTenantMembershipRow struct {
	MembershipID        uuid.UUID          `json:"membership_id"`
	UserID              uuid.UUID          `json:"user_id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	RoleCode            string             `json:"role_code"`
	MembershipStatus    string             `json:"membership_status"`
	MembershipCreatedAt pgtype.Timestamptz `json:"membership_created_at"`
	MembershipUpdatedAt pgtype.Timestamptz `json:"membership_updated_at"`
	UserEmail           string             `json:"user_email"`
	UserDisplayName     string             `json:"user_display_name"`
	UserStatus          string             `json:"user_status"`
	UserGoogleLinked    bool               `json:"user_google_linked"`
}

func (q *Queries) GetTenantMembership(ctx context.Context, id uuid.UUID) (GetTenantMembershipRow, error) {
	row := q.db.QueryRow(ctx, getTenantMembership, id)
	var i GetTenantMembershipRow
	err := row.Scan(
		&i.MembershipID,
		&i.UserID,
		&i.TenantID,
		&i.RoleCode,
		&i.MembershipStatus,
		&i.MembershipCreatedAt,
		&i.MembershipUpdatedAt,
		&i.UserEmail,
		&i.UserDisplayName,
		&i.UserStatus,
		&i.UserGoogleLinked,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_subject, email, display_name, status, created_at, updated_at
FROM platform.users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSubject = `-- name: GetUserByGoogleSubject :one
SELECT id, google_subject, email, display_name, status, created_at, updated_at
FROM platform.users
WHERE google_subject = $1
`

func (q *Queries) GetUserByGoogleSubject(ctx context.Context, googleSubject *string) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSubject, googleSubject)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTenantMembership = `-- name: InsertTenantMembership :one
INSERT INTO platform.tenant_memberships (
    id,
    user_id,
    tenant_id,
    role_code
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, tenant_id, role_code, status, created_at, updated_at
`

type InsertTenantMembershipParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	RoleCode string    `json:"role_code"`
}

func (q *Queries) InsertTenantMembership(ctx context.Context, arg InsertTenantMembershipParams) (PlatformTenantMembership, error) {
	row := q.db.QueryRow(ctx, insertTenantMembership,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.RoleCode,
	)
	var i PlatformTenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkGoogleIdentity = `-- name: LinkGoogleIdentity :one
UPDATE platform.users
SET google_subject = $1,
    email = lower($2),
    display_name = $3,
    status = 'active'
WHERE id = $4
  AND google_subject IS NULL
  AND status = 'pending'
RETURNING id, google_subject, email, display_name, status, created_at, updated_at
`

type LinkGoogleIdentityParams struct {
	GoogleSubject *string   `json:"google_subject"`
	Email         string    `json:"email"`
	DisplayName   string    `json:"display_name"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) LinkGoogleIdentity(ctx context.Context, arg LinkGoogleIdentityParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, linkGoogleIdentity,
		arg.GoogleSubject,
		arg.Email,
		arg.DisplayName,
		arg.ID,
	)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMembershipsByUser = `-- name: ListActiveMembershipsByUser :many
SELECT
    tm.id,
    tm.user_id,
    tm.tenant_id,
    t.slug AS tenant_slug,
    t.name AS tenant_name,
    t.status AS tenant_status,
    tm.role_code,
    tm.status,
    tm.created_at,
    tm.updated_at
FROM platform.tenant_memberships tm
JOIN platform.tenants t ON t.id = tm.tenant_id
WHERE tm.user_id = $1
  AND tm.status = 'active'
  AND t.status = 'active'
ORDER BY t.name, tm.tenant_id
`

type ListActiveMembershipsByUserRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	TenantSlug   string             `json:"tenant_slug"`
	TenantName   string             `json:"tenant_name"`
	TenantStatus string             `json:"tenant_status"`
	RoleCode     string             `json:"role_code"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListActiveMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMembershipsByUserRow
	for rows.Next() {
		var i ListActiveMembershipsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.TenantSlug,
			&i.TenantName,
			&i.TenantStatus,
			&i.RoleCode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyIDsByTenant = `-- name: ListCompanyIDsByTenant :many
SELECT id
FROM organization.companies
WHERE tenant_id = $1
  AND status <> 'archived'
ORDER BY id
`

func (q *Queries) ListCompanyIDsByTenant(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCompanyIDsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipCompanyAccess = `-- name: ListMembershipCompanyAccess :many
SELECT company_id
FROM platform.membership_company_access
WHERE membership_id = $1
  AND tenant_id = $2
ORDER BY company_id
`

type ListMembershipCompanyAccessParams struct {
	MembershipID uuid.UUID `json:"membership_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListMembershipCompanyAccess(ctx context.Context, arg ListMembershipCompanyAccessParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMembershipCompanyAccess, arg.MembershipID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var company_id uuid.UUID
		if err := rows.Scan(&company_id); err != nil {
			return nil, err
		}
		items = append(items, company_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformUsers = `-- name: ListPlatformUsers :many
SELECT id, google_subject, email, display_name, status, created_at, updated_at
FROM platform.users
WHERE ($1::platform.uuid_v7 IS NULL OR id < $1::platform.uuid_v7)
  AND (
      $2::text IS NULL
      OR lower(email) LIKE '%' || lower($2::text) || '%'
      OR lower(display_name) LIKE '%' || lower($2::text) || '%'
  )
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY id DESC
LIMIT $4
`

type ListPlatformUsersParams struct {
	CursorID *uuid.UUID `json:"cursor_id"`
	Search   *string    `json:"search"`
	Status   *string    `json:"status"`
	Limit    int32      `json:"limit"`
}

func (q *Queries) ListPlatformUsers(ctx context.Context, arg ListPlatformUsersParams) ([]PlatformUser, error) {
	rows, err := q.db.Query(ctx, listPlatformUsers,
		arg.CursorID,
		arg.Search,
		arg.Status,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformUser
	for rows.Next() {
		var i PlatformUser
		if err := rows.Scan(
			&i.ID,
			&i.GoogleSubject,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantMemberships = `-- name: ListTenantMemberships :many
SELECT
    tm.id AS membership_id,
    tm.user_id,
    tm.tenant_id,
    tm.role_code,
    tm.status AS membership_status,
    tm.created_at AS membership_created_at,
    tm.updated_at AS membership_updated_at,
    u.email AS user_email,
    u.display_name AS user_display_name,
    u.status AS user_status,
    CASE WHEN u.google_subject IS NULL THEN false ELSE true END AS user_google_linked
FROM platform.tenant_memberships tm
JOIN platform.users u ON u.id = tm.user_id
WHERE tm.tenant_id = $1
  AND ($2::platform.uuid_v7 IS NULL OR tm.id < $2::platform.uuid_v7)
ORDER BY tm.id DESC
LIMIT $3
`

type ListTenantMembershipsParams struct {
	TenantID uuid.UUID  `json:"tenant_id"`
	CursorID *uuid.UUID `json:"cursor_id"`
	Limit    int32      `json:"limit"`
}

type ListTenantMembershipsRow struct {
	MembershipID        uuid.UUID          `json:"membership_id"`
	UserID              uuid.UUID          `json:"user_id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	RoleCode            string             `json:"role_code"`
	MembershipStatus    string             `json:"membership_status"`
	MembershipCreatedAt pgtype.Timestamptz `json:"membership_created_at"`
	MembershipUpdatedAt pgtype.Timestamptz `json:"membership_updated_at"`
	UserEmail           string             `json:"user_email"`
	UserDisplayName     string             `json:"user_display_name"`
	UserStatus          string             `json:"user_status"`
	UserGoogleLinked    bool               `json:"user_google_linked"`
}

func (q *Queries) ListTenantMemberships(ctx context.Context, arg ListTenantMembershipsParams) ([]ListTenantMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listTenantMemberships, arg.TenantID, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantMembershipsRow
	for rows.Next() {
		var i ListTenantMembershipsRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.TenantID,
			&i.RoleCode,
			&i.MembershipStatus,
			&i.MembershipCreatedAt,
			&i.MembershipUpdatedAt,
			&i.UserEmail,
			&i.UserDisplayName,
			&i.UserStatus,
			&i.UserGoogleLinked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateTenantMembership = `-- name: ReactivateTenantMembership :one
UPDATE platform.tenant_memberships
SET status = 'active'
WHERE id = $1
RETURNING id, user_id, tenant_id, role_code, status, created_at, updated_at
`

func (q *Queries) ReactivateTenantMembership(ctx context.Context, id uuid.UUID) (PlatformTenantMembership, error) {
	row := q.db.QueryRow(ctx, reactivateTenantMembership, id)
	var i PlatformTenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE platform.sessions
SET revoked_at = clock_timestamp()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, revokeSession, id)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeTenantMembership = `-- name: RevokeTenantMembership :one
UPDATE platform.tenant_memberships
SET status = 'revoked'
WHERE id = $1
RETURNING id, user_id, tenant_id, role_code, status, created_at, updated_at
`

func (q *Queries) RevokeTenantMembership(ctx context.Context, id uuid.UUID) (PlatformTenantMembership, error) {
	row := q.db.QueryRow(ctx, revokeTenantMembership, id)
	var i PlatformTenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE platform.sessions
SET last_seen_at = clock_timestamp()
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > clock_timestamp()
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, touchSession, id)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateGoogleUserProfile = `-- name: UpdateGoogleUserProfile :one
UPDATE platform.users
SET email = lower($1),
    display_name = $2
WHERE id = $3
  AND google_subject = $4
RETURNING id, google_subject, email, display_name, status, created_at, updated_at
`

type UpdateGoogleUserProfileParams struct {
	Email         string    `json:"email"`
	DisplayName   string    `json:"display_name"`
	ID            uuid.UUID `json:"id"`
	GoogleSubject *string   `json:"google_subject"`
}

func (q *Queries) UpdateGoogleUserProfile(ctx context.Context, arg UpdateGoogleUserProfileParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, updateGoogleUserProfile,
		arg.Email,
		arg.DisplayName,
		arg.ID,
		arg.GoogleSubject,
	)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantMembershipRole = `-- name: UpdateTenantMembershipRole :one
UPDATE platform.tenant_memberships
SET role_code = $1
WHERE id = $2
RETURNING id, user_id, tenant_id, role_code, status, created_at, updated_at
`

type UpdateTenantMembershipRoleParams struct {
	RoleCode string    `json:"role_code"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTenantMembershipRole(ctx context.Context, arg UpdateTenantMembershipRoleParams) (PlatformTenantMembership, error) {
	row := q.db.QueryRow(ctx, updateTenantMembershipRole, arg.RoleCode, arg.ID)
	var i PlatformTenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :one
INSERT INTO platform.users (
    id,
    google_subject,
    email,
    display_name
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (google_subject)
DO UPDATE SET
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name
RETURNING id, google_subject, email, display_name, status, created_at, updated_at
`

type UpsertGoogleUserParams struct {
	ID            uuid.UUID `json:"id"`
	GoogleSubject *string   `json:"google_subject"`
	Email         string    `json:"email"`
	DisplayName   string    `json:"display_name"`
}

func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUser,
		arg.ID,
		arg.GoogleSubject,
		arg.Email,
		arg.DisplayName,
	)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlatformAdmin = `-- name: UpsertPlatformAdmin :one
INSERT INTO platform.platform_admins (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING user_id
`

func (q *Queries) UpsertPlatformAdmin(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPlatformAdmin, userID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
