// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimBackgroundJob = `-- name: ClaimBackgroundJob :one
WITH candidate AS (
    SELECT id
    FROM platform.background_jobs AS candidate_job
    WHERE candidate_job.queue_name = $3
      AND (
          (candidate_job.status IN ('queued', 'retry_scheduled') AND candidate_job.available_at <= clock_timestamp())
          OR
          (candidate_job.status = 'running' AND candidate_job.lease_until < clock_timestamp())
      )
    ORDER BY candidate_job.priority DESC, candidate_job.available_at ASC, candidate_job.id ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE platform.background_jobs AS job
SET status = 'running',
    lease_owner = $1,
    lease_until = clock_timestamp() + $2::interval,
    heartbeat_at = clock_timestamp(),
    attempt_count = job.attempt_count + 1,
    started_at = COALESCE(job.started_at, clock_timestamp()),
    updated_at = clock_timestamp()
FROM candidate
WHERE job.id = candidate.id
RETURNING job.id, job.tenant_id, job.company_id, job.job_type, job.queue_name, job.status, job.priority, job.payload, job.idempotency_key, job.available_at, job.attempt_count, job.max_attempts, job.lease_owner, job.lease_until, job.heartbeat_at, job.last_error_code, job.last_error_message, job.created_at, job.started_at, job.completed_at, job.updated_at
`

type ClaimBackgroundJobParams struct {
	WorkerID      *string         `json:"worker_id"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
	QueueName     string          `json:"queue_name"`
}

func (q *Queries) ClaimBackgroundJob(ctx context.Context, arg ClaimBackgroundJobParams) (PlatformBackgroundJob, error) {
	row := q.db.QueryRow(ctx, claimBackgroundJob, arg.WorkerID, arg.LeaseDuration, arg.QueueName)
	var i PlatformBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.JobType,
		&i.QueueName,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBackgroundJob = `-- name: CreateBackgroundJob :one
INSERT INTO platform.background_jobs (
    id, tenant_id, company_id, job_type, queue_name, payload, idempotency_key,
    available_at, max_attempts
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
RETURNING id, tenant_id, company_id, job_type, queue_name, status, priority, payload, idempotency_key, available_at, attempt_count, max_attempts, lease_owner, lease_until, heartbeat_at, last_error_code, last_error_message, created_at, started_at, completed_at, updated_at
`

type CreateBackgroundJobParams struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       *uuid.UUID         `json:"tenant_id"`
	CompanyID      *uuid.UUID         `json:"company_id"`
	JobType        string             `json:"job_type"`
	QueueName      string             `json:"queue_name"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey *string            `json:"idempotency_key"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	MaxAttempts    int32              `json:"max_attempts"`
}

func (q *Queries) CreateBackgroundJob(ctx context.Context, arg CreateBackgroundJobParams) (PlatformBackgroundJob, error) {
	row := q.db.QueryRow(ctx, createBackgroundJob,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.JobType,
		arg.QueueName,
		arg.Payload,
		arg.IdempotencyKey,
		arg.AvailableAt,
		arg.MaxAttempts,
	)
	var i PlatformBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.JobType,
		&i.QueueName,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBackgroundJobAttempt = `-- name: CreateBackgroundJobAttempt :one
INSERT INTO platform.background_job_attempts (id, job_id, attempt_number, worker_id)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, attempt_number, worker_id, started_at, finished_at, heartbeat_at, outcome, error_code, error_message
`

type CreateBackgroundJobAttemptParams struct {
	ID            uuid.UUID `json:"id"`
	JobID         uuid.UUID `json:"job_id"`
	AttemptNumber int32     `json:"attempt_number"`
	WorkerID      string    `json:"worker_id"`
}

func (q *Queries) CreateBackgroundJobAttempt(ctx context.Context, arg CreateBackgroundJobAttemptParams) (PlatformBackgroundJobAttempt, error) {
	row := q.db.QueryRow(ctx, createBackgroundJobAttempt,
		arg.ID,
		arg.JobID,
		arg.AttemptNumber,
		arg.WorkerID,
	)
	var i PlatformBackgroundJobAttempt
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
		&i.Outcome,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const finishBackgroundJobAttempt = `-- name: FinishBackgroundJobAttempt :exec
UPDATE platform.background_job_attempts
SET finished_at = clock_timestamp(),
    outcome = $1,
    error_code = $2,
    error_message = $3
WHERE job_id = $4
  AND attempt_number = $5
`

type FinishBackgroundJobAttemptParams struct {
	Outcome       *string   `json:"outcome"`
	ErrorCode     *string   `json:"error_code"`
	ErrorMessage  *string   `json:"error_message"`
	JobID         uuid.UUID `json:"job_id"`
	AttemptNumber int32     `json:"attempt_number"`
}

func (q *Queries) FinishBackgroundJobAttempt(ctx context.Context, arg FinishBackgroundJobAttemptParams) error {
	_, err := q.db.Exec(ctx, finishBackgroundJobAttempt,
		arg.Outcome,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.JobID,
		arg.AttemptNumber,
	)
	return err
}

const getBackgroundJob = `-- name: GetBackgroundJob :one
SELECT id, tenant_id, company_id, job_type, queue_name, status, priority, payload, idempotency_key, available_at, attempt_count, max_attempts, lease_owner, lease_until, heartbeat_at, last_error_code, last_error_message, created_at, started_at, completed_at, updated_at
FROM platform.background_jobs
WHERE id = $1
`

func (q *Queries) GetBackgroundJob(ctx context.Context, id uuid.UUID) (PlatformBackgroundJob, error) {
	row := q.db.QueryRow(ctx, getBackgroundJob, id)
	var i PlatformBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.JobType,
		&i.QueueName,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatBackgroundJob = `-- name: HeartbeatBackgroundJob :exec
UPDATE platform.background_jobs
SET lease_until = clock_timestamp() + $1::interval,
    heartbeat_at = clock_timestamp()
WHERE id = $2
  AND status = 'running'
  AND lease_owner = $3
`

type HeartbeatBackgroundJobParams struct {
	LeaseDuration pgtype.Interval `json:"lease_duration"`
	ID            uuid.UUID       `json:"id"`
	WorkerID      *string         `json:"worker_id"`
}

func (q *Queries) HeartbeatBackgroundJob(ctx context.Context, arg HeartbeatBackgroundJobParams) error {
	_, err := q.db.Exec(ctx, heartbeatBackgroundJob, arg.LeaseDuration, arg.ID, arg.WorkerID)
	return err
}

const markBackgroundJobCanceled = `-- name: MarkBackgroundJobCanceled :one
UPDATE platform.background_jobs
SET status = 'canceled',
    lease_owner = NULL,
    lease_until = NULL,
    heartbeat_at = NULL,
    completed_at = clock_timestamp()
WHERE id = $1
  AND status IN ('running', 'cancel_requested')
  AND (lease_owner = $2 OR status = 'cancel_requested')
RETURNING id, tenant_id, company_id, job_type, queue_name, status, priority, payload, idempotency_key, available_at, attempt_count, max_attempts, lease_owner, lease_until, heartbeat_at, last_error_code, last_error_message, created_at, started_at, completed_at, updated_at
`

type MarkBackgroundJobCanceledParams struct {
	ID       uuid.UUID `json:"id"`
	WorkerID *string   `json:"worker_id"`
}

func (q *Queries) MarkBackgroundJobCanceled(ctx context.Context, arg MarkBackgroundJobCanceledParams) (PlatformBackgroundJob, error) {
	row := q.db.QueryRow(ctx, markBackgroundJobCanceled, arg.ID, arg.WorkerID)
	var i PlatformBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.JobType,
		&i.QueueName,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBackgroundJobFailed = `-- name: MarkBackgroundJobFailed :one
UPDATE platform.background_jobs
SET status = CASE WHEN attempt_count >= max_attempts THEN 'dead_letter' ELSE 'failed' END,
    lease_owner = NULL,
    lease_until = NULL,
    heartbeat_at = NULL,
    completed_at = clock_timestamp(),
    last_error_code = $1,
    last_error_message = $2
WHERE id = $3
  AND status = 'running'
  AND lease_owner = $4
RETURNING id, tenant_id, company_id, job_type, queue_name, status, priority, payload, idempotency_key, available_at, attempt_count, max_attempts, lease_owner, lease_until, heartbeat_at, last_error_code, last_error_message, created_at, started_at, completed_at, updated_at
`

type MarkBackgroundJobFailedParams struct {
	ErrorCode    *string   `json:"error_code"`
	ErrorMessage *string   `json:"error_message"`
	ID           uuid.UUID `json:"id"`
	WorkerID     *string   `json:"worker_id"`
}

func (q *Queries) MarkBackgroundJobFailed(ctx context.Context, arg MarkBackgroundJobFailedParams) (PlatformBackgroundJob, error) {
	row := q.db.QueryRow(ctx, markBackgroundJobFailed,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.WorkerID,
	)
	var i PlatformBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.JobType,
		&i.QueueName,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBackgroundJobRetry = `-- name: MarkBackgroundJobRetry :one
UPDATE platform.background_jobs
SET status = 'retry_scheduled',
    available_at = $1,
    lease_owner = NULL,
    lease_until = NULL,
    heartbeat_at = NULL,
    last_error_code = $2,
    last_error_message = $3
WHERE id = $4
  AND status = 'running'
  AND lease_owner = $5
RETURNING id, tenant_id, company_id, job_type, queue_name, status, priority, payload, idempotency_key, available_at, attempt_count, max_attempts, lease_owner, lease_until, heartbeat_at, last_error_code, last_error_message, created_at, started_at, completed_at, updated_at
`

type MarkBackgroundJobRetryParams struct {
	AvailableAt  pgtype.Timestamptz `json:"available_at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	ID           uuid.UUID          `json:"id"`
	WorkerID     *string            `json:"worker_id"`
}

func (q *Queries) MarkBackgroundJobRetry(ctx context.Context, arg MarkBackgroundJobRetryParams) (PlatformBackgroundJob, error) {
	row := q.db.QueryRow(ctx, markBackgroundJobRetry,
		arg.AvailableAt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.WorkerID,
	)
	var i PlatformBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.JobType,
		&i.QueueName,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBackgroundJobSucceeded = `-- name: MarkBackgroundJobSucceeded :one
UPDATE platform.background_jobs
SET status = 'succeeded',
    lease_owner = NULL,
    lease_until = NULL,
    heartbeat_at = NULL,
    completed_at = clock_timestamp()
WHERE id = $1
  AND status = 'running'
  AND lease_owner = $2
RETURNING id, tenant_id, company_id, job_type, queue_name, status, priority, payload, idempotency_key, available_at, attempt_count, max_attempts, lease_owner, lease_until, heartbeat_at, last_error_code, last_error_message, created_at, started_at, completed_at, updated_at
`

type MarkBackgroundJobSucceededParams struct {
	ID       uuid.UUID `json:"id"`
	WorkerID *string   `json:"worker_id"`
}

func (q *Queries) MarkBackgroundJobSucceeded(ctx context.Context, arg MarkBackgroundJobSucceededParams) (PlatformBackgroundJob, error) {
	row := q.db.QueryRow(ctx, markBackgroundJobSucceeded, arg.ID, arg.WorkerID)
	var i PlatformBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.JobType,
		&i.QueueName,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestBackgroundJobCancellation = `-- name: RequestBackgroundJobCancellation :one
UPDATE platform.background_jobs
SET status = CASE WHEN status = 'queued' OR status = 'retry_scheduled' THEN 'canceled' ELSE 'cancel_requested' END,
    completed_at = CASE WHEN status = 'queued' OR status = 'retry_scheduled' THEN clock_timestamp() ELSE completed_at END
WHERE id = $1
  AND status IN ('queued', 'retry_scheduled', 'running')
RETURNING id, tenant_id, company_id, job_type, queue_name, status, priority, payload, idempotency_key, available_at, attempt_count, max_attempts, lease_owner, lease_until, heartbeat_at, last_error_code, last_error_message, created_at, started_at, completed_at, updated_at
`

func (q *Queries) RequestBackgroundJobCancellation(ctx context.Context, id uuid.UUID) (PlatformBackgroundJob, error) {
	row := q.db.QueryRow(ctx, requestBackgroundJobCancellation, id)
	var i PlatformBackgroundJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.JobType,
		&i.QueueName,
		&i.Status,
		&i.Priority,
		&i.Payload,
		&i.IdempotencyKey,
		&i.AvailableAt,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.HeartbeatAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
