// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Person identity and mutable personal data. NIK is encrypted and indexed only by an application-generated keyed hash.
type EmployeeEmployee struct {
	ID uuid.UUID `json:"id"`
	// Company-scoped organization employee number. It is immutable after creation.
	EmployeeNumber string `json:"employee_number"`
	// Application-encrypted NIK ciphertext. Encryption keys are never stored in PostgreSQL.
	NikCiphertext []byte `json:"nik_ciphertext"`
	// Stable HMAC-SHA-256 lookup value for exact-match uniqueness; not a plain hash of NIK.
	NikLookupHash []byte             `json:"nik_lookup_hash"`
	FullName      string             `json:"full_name"`
	BirthPlace    *string            `json:"birth_place"`
	BirthDate     pgtype.Date        `json:"birth_date"`
	Gender        *string            `json:"gender"`
	Email         *string            `json:"email"`
	Phone         *string            `json:"phone"`
	Address       *string            `json:"address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	// SaaS isolation owner. It is immutable after creation.
	TenantID uuid.UUID `json:"tenant_id"`
	// Legal/payroll company owner. It is immutable after creation and scopes employee number and NIK uniqueness.
	CompanyID uuid.UUID `json:"company_id"`
}

// Effective-dated organizational placement. effective_to is inclusive; a new assignment closes the preceding assignment at the previous day.
type EmployeeEmployeeAssignment struct {
	ID           uuid.UUID `json:"id"`
	EmploymentID uuid.UUID `json:"employment_id"`
	// References an organization-managed location. No FK is created until the organization schema is available.
	LocationID *uuid.UUID `json:"location_id"`
	// References an organization-managed department. No FK is created until the organization schema is available.
	DepartmentID *uuid.UUID `json:"department_id"`
	// References an organization-managed position. No FK is created until the organization schema is available.
	PositionID *uuid.UUID `json:"position_id"`
	// References an organization-managed group. No FK is created until the organization schema is available.
	GroupID       *uuid.UUID         `json:"group_id"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	EffectiveTo   pgtype.Date        `json:"effective_to"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// One continuous employment relationship. end_date is the inclusive last working date.
type EmployeeEmployment struct {
	ID         uuid.UUID `json:"id"`
	EmployeeID uuid.UUID `json:"employee_id"`
	// References the organization company identity. The organization module owns the referenced table; no cross-module FK is created here.
	CompanyID         uuid.UUID          `json:"company_id"`
	EmploymentType    string             `json:"employment_type"`
	JoinDate          pgtype.Date        `json:"join_date"`
	EndDate           pgtype.Date        `json:"end_date"`
	TerminationReason *string            `json:"termination_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	// SaaS tenant owner copied from the employee company and immutable.
	TenantID uuid.UUID `json:"tenant_id"`
}

type FileBatchArtifact struct {
	ID           uuid.UUID          `json:"id"`
	BatchID      uuid.UUID          `json:"batch_id"`
	FileObjectID uuid.UUID          `json:"file_object_id"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type FileFileObject struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          *uuid.UUID         `json:"tenant_id"`
	CompanyID         *uuid.UUID         `json:"company_id"`
	StorageProvider   string             `json:"storage_provider"`
	ObjectKey         string             `json:"object_key"`
	OriginalFilename  string             `json:"original_filename"`
	DetectedExtension string             `json:"detected_extension"`
	DetectedMimeType  string             `json:"detected_mime_type"`
	SizeBytes         int64              `json:"size_bytes"`
	Sha256            []byte             `json:"sha256"`
	EncryptionMode    string             `json:"encryption_mode"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	LegalHold         bool               `json:"legal_hold"`
	CreatedBy         *uuid.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type FileImportBatch struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	CompanyID            uuid.UUID          `json:"company_id"`
	Operation            string             `json:"operation"`
	InputFileID          uuid.UUID          `json:"input_file_id"`
	TemplateID           *uuid.UUID         `json:"template_id"`
	CreatedBy            uuid.UUID          `json:"created_by"`
	Status               string             `json:"status"`
	TotalRows            int32              `json:"total_rows"`
	ValidRows            int32              `json:"valid_rows"`
	InvalidRows          int32              `json:"invalid_rows"`
	WarningRows          int32              `json:"warning_rows"`
	CommittedRows        int32              `json:"committed_rows"`
	RejectedRows         int32              `json:"rejected_rows"`
	ValidationStartedAt  pgtype.Timestamptz `json:"validation_started_at"`
	ValidationFinishedAt pgtype.Timestamptz `json:"validation_finished_at"`
	CommitStartedAt      pgtype.Timestamptz `json:"commit_started_at"`
	CommitFinishedAt     pgtype.Timestamptz `json:"commit_finished_at"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type FileImportBatchStep struct {
	ID         uuid.UUID          `json:"id"`
	BatchID    uuid.UUID          `json:"batch_id"`
	StepType   string             `json:"step_type"`
	JobID      uuid.UUID          `json:"job_id"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

type FileImportTemplate struct {
	ID           uuid.UUID          `json:"id"`
	TemplateType string             `json:"template_type"`
	Version      string             `json:"version"`
	FileFormat   string             `json:"file_format"`
	ArtifactID   *uuid.UUID         `json:"artifact_id"`
	Schema       []byte             `json:"schema"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OrganizationCompany struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Code        string             `json:"code"`
	LegalName   string             `json:"legal_name"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationUnit struct {
	ID        uuid.UUID          `json:"id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	CompanyID uuid.UUID          `json:"company_id"`
	UnitType  string             `json:"unit_type"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Company-scoped monthly payroll ledger period. Finalized periods are immutable.
type PayrollPayrollPeriod struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	CompanyID uuid.UUID `json:"company_id"`
	Year      int32     `json:"year"`
	// Calendar month from 1 through 12.
	Month       int32              `json:"month"`
	Status      string             `json:"status"`
	OpenedAt    pgtype.Timestamptz `json:"opened_at"`
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Historical payroll result for one employee in one payroll period.
type PayrollPayrollResult struct {
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	CompanyID       uuid.UUID `json:"company_id"`
	PayrollPeriodID uuid.UUID `json:"payroll_period_id"`
	EmployeeID      uuid.UUID `json:"employee_id"`
	EmploymentID    uuid.UUID `json:"employment_id"`
	GrossIncome     int64     `json:"gross_income"`
	TaxableIncome   int64     `json:"taxable_income"`
	TakeHomePay     int64     `json:"take_home_pay"`
	// Set when the containing payroll period is finalized; finalized results cannot be edited.
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Normalized payroll component amounts. Component codes are stable import/domain codes.
type PayrollPayrollResultItem struct {
	ID              uuid.UUID          `json:"id"`
	PayrollResultID uuid.UUID          `json:"payroll_result_id"`
	ComponentCode   string             `json:"component_code"`
	ComponentType   string             `json:"component_type"`
	Amount          int64              `json:"amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PlatformBackgroundJob struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         *uuid.UUID         `json:"tenant_id"`
	CompanyID        *uuid.UUID         `json:"company_id"`
	JobType          string             `json:"job_type"`
	QueueName        string             `json:"queue_name"`
	Status           string             `json:"status"`
	Priority         int32              `json:"priority"`
	Payload          []byte             `json:"payload"`
	IdempotencyKey   *string            `json:"idempotency_key"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	AttemptCount     int32              `json:"attempt_count"`
	MaxAttempts      int32              `json:"max_attempts"`
	LeaseOwner       *string            `json:"lease_owner"`
	LeaseUntil       pgtype.Timestamptz `json:"lease_until"`
	HeartbeatAt      pgtype.Timestamptz `json:"heartbeat_at"`
	LastErrorCode    *string            `json:"last_error_code"`
	LastErrorMessage *string            `json:"last_error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PlatformBackgroundJobAttempt struct {
	ID            uuid.UUID          `json:"id"`
	JobID         uuid.UUID          `json:"job_id"`
	AttemptNumber int32              `json:"attempt_number"`
	WorkerID      string             `json:"worker_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	HeartbeatAt   pgtype.Timestamptz `json:"heartbeat_at"`
	Outcome       *string            `json:"outcome"`
	ErrorCode     *string            `json:"error_code"`
	ErrorMessage  *string            `json:"error_message"`
}

type PlatformMembershipCompanyAccess struct {
	MembershipID uuid.UUID          `json:"membership_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PlatformPlatformAdmin struct {
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PlatformSession struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type PlatformTenant struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlatformTenantMembership struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TenantID  uuid.UUID          `json:"tenant_id"`
	RoleCode  string             `json:"role_code"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlatformUser struct {
	ID            uuid.UUID          `json:"id"`
	GoogleSubject *string            `json:"google_subject"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Historical tax profile snapshots. Profile values are encrypted and are never recalculated from current employee data.
type TaxEmployeeTaxProfile struct {
	ID         uuid.UUID `json:"id"`
	EmployeeID uuid.UUID `json:"employee_id"`
	// Encrypted NIK snapshot effective for this tax profile period.
	NikCiphertext []byte `json:"nik_ciphertext"`
	// Encrypted NPWP snapshot effective for this tax profile period.
	NpwpCiphertext []byte      `json:"npwp_ciphertext"`
	PtkpCode       string      `json:"ptkp_code"`
	TaxMethod      string      `json:"tax_method"`
	EffectiveFrom  pgtype.Date `json:"effective_from"`
	// Inclusive end date. A new profile closes the prior open profile at the previous day.
	EffectiveTo pgtype.Date        `json:"effective_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	CompanyID   uuid.UUID          `json:"company_id"`
}
