// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: organization.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const archiveUnit = `-- name: ArchiveUnit :one
UPDATE organization.units
SET status = 'archived'
WHERE id = $1 AND status <> 'archived'
RETURNING id, tenant_id, company_id, unit_type, code, name, status, created_at, updated_at
`

func (q *Queries) ArchiveUnit(ctx context.Context, id uuid.UUID) (OrganizationUnit, error) {
	row := q.db.QueryRow(ctx, archiveUnit, id)
	var i OrganizationUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.UnitType,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO organization.companies (id, tenant_id, code, legal_name, display_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, code, legal_name, display_name, status, created_at, updated_at
`

type CreateCompanyParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Code        string    `json:"code"`
	LegalName   string    `json:"legal_name"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (OrganizationCompany, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.LegalName,
		arg.DisplayName,
	)
	var i OrganizationCompany
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.LegalName,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO platform.tenants (id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, slug, name, status, created_at, updated_at
`

type CreateTenantParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (PlatformTenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Slug, arg.Name)
	var i PlatformTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO organization.units (id, tenant_id, company_id, unit_type, code, name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, company_id, unit_type, code, name, status, created_at, updated_at
`

type CreateUnitParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	CompanyID uuid.UUID `json:"company_id"`
	UnitType  string    `json:"unit_type"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (OrganizationUnit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.UnitType,
		arg.Code,
		arg.Name,
	)
	var i OrganizationUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.UnitType,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, tenant_id, code, legal_name, display_name, status, created_at, updated_at FROM organization.companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id uuid.UUID) (OrganizationCompany, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i OrganizationCompany
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.LegalName,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, slug, name, status, created_at, updated_at FROM platform.tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (PlatformTenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i PlatformTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, tenant_id, company_id, unit_type, code, name, status, created_at, updated_at FROM organization.units WHERE id = $1
`

func (q *Queries) GetUnit(ctx context.Context, id uuid.UUID) (OrganizationUnit, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i OrganizationUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.UnitType,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, tenant_id, code, legal_name, display_name, status, created_at, updated_at FROM organization.companies
WHERE tenant_id = $1
  AND ($2::platform.uuid_v7 IS NULL OR id < $2::platform.uuid_v7)
ORDER BY id DESC
LIMIT $3
`

type ListCompaniesParams struct {
	TenantID uuid.UUID  `json:"tenant_id"`
	CursorID *uuid.UUID `json:"cursor_id"`
	Limit    int32      `json:"limit"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]OrganizationCompany, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.TenantID, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationCompany
	for rows.Next() {
		var i OrganizationCompany
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.LegalName,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, name, status, created_at, updated_at FROM platform.tenants
WHERE ($1::platform.uuid_v7 IS NULL OR id < $1::platform.uuid_v7)
ORDER BY id DESC
LIMIT $2
`

type ListTenantsParams struct {
	CursorID *uuid.UUID `json:"cursor_id"`
	Limit    int32      `json:"limit"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]PlatformTenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformTenant
	for rows.Next() {
		var i PlatformTenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, tenant_id, company_id, unit_type, code, name, status, created_at, updated_at FROM organization.units
WHERE tenant_id = $1
  AND unit_type = $2
  AND ($3::platform.uuid_v7 IS NULL OR company_id = $3::platform.uuid_v7)
  AND ($4::platform.uuid_v7 IS NULL OR id < $4::platform.uuid_v7)
ORDER BY id DESC
LIMIT $5
`

type ListUnitsParams struct {
	TenantID  uuid.UUID  `json:"tenant_id"`
	UnitType  string     `json:"unit_type"`
	CompanyID *uuid.UUID `json:"company_id"`
	CursorID  *uuid.UUID `json:"cursor_id"`
	Limit     int32      `json:"limit"`
}

func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]OrganizationUnit, error) {
	rows, err := q.db.Query(ctx, listUnits,
		arg.TenantID,
		arg.UnitType,
		arg.CompanyID,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationUnit
	for rows.Next() {
		var i OrganizationUnit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyID,
			&i.UnitType,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionCompany = `-- name: TransitionCompany :one
UPDATE organization.companies
SET status = $1
WHERE id = $2
RETURNING id, tenant_id, code, legal_name, display_name, status, created_at, updated_at
`

type TransitionCompanyParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) TransitionCompany(ctx context.Context, arg TransitionCompanyParams) (OrganizationCompany, error) {
	row := q.db.QueryRow(ctx, transitionCompany, arg.Status, arg.ID)
	var i OrganizationCompany
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.LegalName,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionTenant = `-- name: TransitionTenant :one
UPDATE platform.tenants
SET status = $1
WHERE id = $2
RETURNING id, slug, name, status, created_at, updated_at
`

type TransitionTenantParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) TransitionTenant(ctx context.Context, arg TransitionTenantParams) (PlatformTenant, error) {
	row := q.db.QueryRow(ctx, transitionTenant, arg.Status, arg.ID)
	var i PlatformTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE organization.companies
SET code = $1, legal_name = $2, display_name = $3
WHERE id = $4
RETURNING id, tenant_id, code, legal_name, display_name, status, created_at, updated_at
`

type UpdateCompanyParams struct {
	Code        string    `json:"code"`
	LegalName   string    `json:"legal_name"`
	DisplayName string    `json:"display_name"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (OrganizationCompany, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Code,
		arg.LegalName,
		arg.DisplayName,
		arg.ID,
	)
	var i OrganizationCompany
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.LegalName,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE platform.tenants
SET name = $1
WHERE id = $2
RETURNING id, slug, name, status, created_at, updated_at
`

type UpdateTenantParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (PlatformTenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.Name, arg.ID)
	var i PlatformTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE organization.units
SET code = $1, name = $2
WHERE id = $3
RETURNING id, tenant_id, company_id, unit_type, code, name, status, created_at, updated_at
`

type UpdateUnitParams struct {
	Code string    `json:"code"`
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (OrganizationUnit, error) {
	row := q.db.QueryRow(ctx, updateUnit, arg.Code, arg.Name, arg.ID)
	var i OrganizationUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.UnitType,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
