// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payroll.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPayrollResults = `-- name: CountPayrollResults :one
SELECT count(*)::bigint
FROM payroll.payroll_results
WHERE payroll_period_id = $1
`

func (q *Queries) CountPayrollResults(ctx context.Context, payrollPeriodID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPayrollResults, payrollPeriodID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPayrollPeriod = `-- name: CreatePayrollPeriod :one
INSERT INTO payroll.payroll_periods (id, tenant_id, company_id, year, month)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, company_id, year, month, status, opened_at, finalized_at, created_at, updated_at
`

type CreatePayrollPeriodParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	CompanyID uuid.UUID `json:"company_id"`
	Year      int32     `json:"year"`
	Month     int32     `json:"month"`
}

func (q *Queries) CreatePayrollPeriod(ctx context.Context, arg CreatePayrollPeriodParams) (PayrollPayrollPeriod, error) {
	row := q.db.QueryRow(ctx, createPayrollPeriod,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.Year,
		arg.Month,
	)
	var i PayrollPayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.OpenedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayrollResult = `-- name: CreatePayrollResult :one
INSERT INTO payroll.payroll_results (
    id,
    tenant_id,
    company_id,
    payroll_period_id,
    employee_id,
    employment_id,
    gross_income,
    taxable_income,
    take_home_pay, payroll_run_id, source_employee_number, source_sheet_name, source_row_no
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9, $10, $11,
    $12, $13
)
RETURNING id, tenant_id, company_id, payroll_period_id, employee_id, employment_id, gross_income, taxable_income, take_home_pay, finalized_at, created_at, updated_at, payroll_run_id, source_employee_number, source_sheet_name, source_row_no
`

type CreatePayrollResultParams struct {
	ID                   uuid.UUID  `json:"id"`
	TenantID             uuid.UUID  `json:"tenant_id"`
	CompanyID            uuid.UUID  `json:"company_id"`
	PayrollPeriodID      uuid.UUID  `json:"payroll_period_id"`
	EmployeeID           uuid.UUID  `json:"employee_id"`
	EmploymentID         uuid.UUID  `json:"employment_id"`
	GrossIncome          int64      `json:"gross_income"`
	TaxableIncome        int64      `json:"taxable_income"`
	TakeHomePay          int64      `json:"take_home_pay"`
	PayrollRunID         *uuid.UUID `json:"payroll_run_id"`
	SourceEmployeeNumber *string    `json:"source_employee_number"`
	SourceSheetName      *string    `json:"source_sheet_name"`
	SourceRowNo          *int32     `json:"source_row_no"`
}

func (q *Queries) CreatePayrollResult(ctx context.Context, arg CreatePayrollResultParams) (PayrollPayrollResult, error) {
	row := q.db.QueryRow(ctx, createPayrollResult,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.PayrollPeriodID,
		arg.EmployeeID,
		arg.EmploymentID,
		arg.GrossIncome,
		arg.TaxableIncome,
		arg.TakeHomePay,
		arg.PayrollRunID,
		arg.SourceEmployeeNumber,
		arg.SourceSheetName,
		arg.SourceRowNo,
	)
	var i PayrollPayrollResult
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.PayrollPeriodID,
		&i.EmployeeID,
		&i.EmploymentID,
		&i.GrossIncome,
		&i.TaxableIncome,
		&i.TakeHomePay,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PayrollRunID,
		&i.SourceEmployeeNumber,
		&i.SourceSheetName,
		&i.SourceRowNo,
	)
	return i, err
}

const createPayrollResultItem = `-- name: CreatePayrollResultItem :one
INSERT INTO payroll.payroll_result_items (id, payroll_result_id, component_code, component_type, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, payroll_result_id, component_code, component_type, amount, created_at, updated_at
`

type CreatePayrollResultItemParams struct {
	ID              uuid.UUID `json:"id"`
	PayrollResultID uuid.UUID `json:"payroll_result_id"`
	ComponentCode   string    `json:"component_code"`
	ComponentType   string    `json:"component_type"`
	Amount          int64     `json:"amount"`
}

func (q *Queries) CreatePayrollResultItem(ctx context.Context, arg CreatePayrollResultItemParams) (PayrollPayrollResultItem, error) {
	row := q.db.QueryRow(ctx, createPayrollResultItem,
		arg.ID,
		arg.PayrollResultID,
		arg.ComponentCode,
		arg.ComponentType,
		arg.Amount,
	)
	var i PayrollPayrollResultItem
	err := row.Scan(
		&i.ID,
		&i.PayrollResultID,
		&i.ComponentCode,
		&i.ComponentType,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayrollRun = `-- name: CreatePayrollRun :one
INSERT INTO payroll.payroll_runs (
    id, tenant_id, company_id, payroll_period_id, run_type, run_date,
    coverage_from, coverage_to, pay_date, sequence_no, source_batch_id,
    correction_of_run_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, tenant_id, company_id, payroll_period_id, run_type, run_date, sequence_no, source_batch_id, correction_of_run_id, status, finalized_at, created_at, updated_at, coverage_from, coverage_to, pay_date
`

type CreatePayrollRunParams struct {
	ID                uuid.UUID   `json:"id"`
	TenantID          uuid.UUID   `json:"tenant_id"`
	CompanyID         uuid.UUID   `json:"company_id"`
	PayrollPeriodID   uuid.UUID   `json:"payroll_period_id"`
	RunType           string      `json:"run_type"`
	RunDate           pgtype.Date `json:"run_date"`
	CoverageFrom      pgtype.Date `json:"coverage_from"`
	CoverageTo        pgtype.Date `json:"coverage_to"`
	PayDate           pgtype.Date `json:"pay_date"`
	SequenceNo        int32       `json:"sequence_no"`
	SourceBatchID     *uuid.UUID  `json:"source_batch_id"`
	CorrectionOfRunID *uuid.UUID  `json:"correction_of_run_id"`
}

func (q *Queries) CreatePayrollRun(ctx context.Context, arg CreatePayrollRunParams) (PayrollPayrollRun, error) {
	row := q.db.QueryRow(ctx, createPayrollRun,
		arg.ID,
		arg.TenantID,
		arg.CompanyID,
		arg.PayrollPeriodID,
		arg.RunType,
		arg.RunDate,
		arg.CoverageFrom,
		arg.CoverageTo,
		arg.PayDate,
		arg.SequenceNo,
		arg.SourceBatchID,
		arg.CorrectionOfRunID,
	)
	var i PayrollPayrollRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.PayrollPeriodID,
		&i.RunType,
		&i.RunDate,
		&i.SequenceNo,
		&i.SourceBatchID,
		&i.CorrectionOfRunID,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverageFrom,
		&i.CoverageTo,
		&i.PayDate,
	)
	return i, err
}

const finalizePayrollPeriod = `-- name: FinalizePayrollPeriod :one
UPDATE payroll.payroll_periods
SET status = 'finalized', finalized_at = $1
WHERE id = $2
  AND status = 'open'
RETURNING id, tenant_id, company_id, year, month, status, opened_at, finalized_at, created_at, updated_at
`

type FinalizePayrollPeriodParams struct {
	FinalizedAt pgtype.Timestamptz `json:"finalized_at"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) FinalizePayrollPeriod(ctx context.Context, arg FinalizePayrollPeriodParams) (PayrollPayrollPeriod, error) {
	row := q.db.QueryRow(ctx, finalizePayrollPeriod, arg.FinalizedAt, arg.ID)
	var i PayrollPayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.OpenedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizePayrollResults = `-- name: FinalizePayrollResults :exec
UPDATE payroll.payroll_results
SET finalized_at = $1
WHERE payroll_period_id = $2
  AND finalized_at IS NULL
`

type FinalizePayrollResultsParams struct {
	FinalizedAt     pgtype.Timestamptz `json:"finalized_at"`
	PayrollPeriodID uuid.UUID          `json:"payroll_period_id"`
}

func (q *Queries) FinalizePayrollResults(ctx context.Context, arg FinalizePayrollResultsParams) error {
	_, err := q.db.Exec(ctx, finalizePayrollResults, arg.FinalizedAt, arg.PayrollPeriodID)
	return err
}

const getEmployeePayrollReference = `-- name: GetEmployeePayrollReference :one
SELECT company_id
FROM employee.employees
WHERE id = $1
`

func (q *Queries) GetEmployeePayrollReference(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getEmployeePayrollReference, id)
	var company_id uuid.UUID
	err := row.Scan(&company_id)
	return company_id, err
}

const getEmploymentForPayrollCoverage = `-- name: GetEmploymentForPayrollCoverage :one
SELECT id, employee_id, company_id, join_date, end_date
FROM employee.employments
WHERE id = $1
  AND join_date <= $2
  AND (end_date IS NULL OR end_date >= $3)
`

type GetEmploymentForPayrollCoverageParams struct {
	ID           uuid.UUID   `json:"id"`
	CoverageTo   pgtype.Date `json:"coverage_to"`
	CoverageFrom pgtype.Date `json:"coverage_from"`
}

type GetEmploymentForPayrollCoverageRow struct {
	ID         uuid.UUID   `json:"id"`
	EmployeeID uuid.UUID   `json:"employee_id"`
	CompanyID  uuid.UUID   `json:"company_id"`
	JoinDate   pgtype.Date `json:"join_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) GetEmploymentForPayrollCoverage(ctx context.Context, arg GetEmploymentForPayrollCoverageParams) (GetEmploymentForPayrollCoverageRow, error) {
	row := q.db.QueryRow(ctx, getEmploymentForPayrollCoverage, arg.ID, arg.CoverageTo, arg.CoverageFrom)
	var i GetEmploymentForPayrollCoverageRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.JoinDate,
		&i.EndDate,
	)
	return i, err
}

const getEmploymentPayrollReference = `-- name: GetEmploymentPayrollReference :one
SELECT id, employee_id, company_id, join_date, end_date
FROM employee.employments
WHERE id = $1
`

type GetEmploymentPayrollReferenceRow struct {
	ID         uuid.UUID   `json:"id"`
	EmployeeID uuid.UUID   `json:"employee_id"`
	CompanyID  uuid.UUID   `json:"company_id"`
	JoinDate   pgtype.Date `json:"join_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) GetEmploymentPayrollReference(ctx context.Context, id uuid.UUID) (GetEmploymentPayrollReferenceRow, error) {
	row := q.db.QueryRow(ctx, getEmploymentPayrollReference, id)
	var i GetEmploymentPayrollReferenceRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.JoinDate,
		&i.EndDate,
	)
	return i, err
}

const getPayrollPeriod = `-- name: GetPayrollPeriod :one
SELECT id, tenant_id, company_id, year, month, status, opened_at, finalized_at, created_at, updated_at
FROM payroll.payroll_periods
WHERE id = $1
`

func (q *Queries) GetPayrollPeriod(ctx context.Context, id uuid.UUID) (PayrollPayrollPeriod, error) {
	row := q.db.QueryRow(ctx, getPayrollPeriod, id)
	var i PayrollPayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.OpenedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayrollPeriodByTenantCompanyMonth = `-- name: GetPayrollPeriodByTenantCompanyMonth :one
SELECT id, tenant_id, company_id, year, month, status, opened_at, finalized_at, created_at, updated_at FROM payroll.payroll_periods
WHERE tenant_id = $1 AND company_id = $2
  AND year = $3 AND month = $4
`

type GetPayrollPeriodByTenantCompanyMonthParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	CompanyID uuid.UUID `json:"company_id"`
	Year      int32     `json:"year"`
	Month     int32     `json:"month"`
}

func (q *Queries) GetPayrollPeriodByTenantCompanyMonth(ctx context.Context, arg GetPayrollPeriodByTenantCompanyMonthParams) (PayrollPayrollPeriod, error) {
	row := q.db.QueryRow(ctx, getPayrollPeriodByTenantCompanyMonth,
		arg.TenantID,
		arg.CompanyID,
		arg.Year,
		arg.Month,
	)
	var i PayrollPayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.OpenedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayrollPeriodForUpdate = `-- name: GetPayrollPeriodForUpdate :one
SELECT id, tenant_id, company_id, year, month, status, opened_at, finalized_at, created_at, updated_at
FROM payroll.payroll_periods
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPayrollPeriodForUpdate(ctx context.Context, id uuid.UUID) (PayrollPayrollPeriod, error) {
	row := q.db.QueryRow(ctx, getPayrollPeriodForUpdate, id)
	var i PayrollPayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.OpenedAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayrollRun = `-- name: GetPayrollRun :one
SELECT id, tenant_id, company_id, payroll_period_id, run_type, run_date, sequence_no, source_batch_id, correction_of_run_id, status, finalized_at, created_at, updated_at, coverage_from, coverage_to, pay_date FROM payroll.payroll_runs WHERE id = $1
`

func (q *Queries) GetPayrollRun(ctx context.Context, id uuid.UUID) (PayrollPayrollRun, error) {
	row := q.db.QueryRow(ctx, getPayrollRun, id)
	var i PayrollPayrollRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyID,
		&i.PayrollPeriodID,
		&i.RunType,
		&i.RunDate,
		&i.SequenceNo,
		&i.SourceBatchID,
		&i.CorrectionOfRunID,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverageFrom,
		&i.CoverageTo,
		&i.PayDate,
	)
	return i, err
}

const listPayrollHistory = `-- name: ListPayrollHistory :many
SELECT
    pr.id,
    pr.tenant_id,
    pr.company_id,
    pr.payroll_period_id,
    pr.employee_id,
    pr.employment_id,
    pr.gross_income,
    pr.taxable_income,
    pr.take_home_pay,
    pr.finalized_at,
    pr.created_at,
    pr.updated_at,
    pp.year AS period_year,
    pp.month AS period_month,
    pp.status AS period_status,
    pp.opened_at AS period_opened_at,
    pp.finalized_at AS period_finalized_at,
    pp.created_at AS period_created_at,
    pp.updated_at AS period_updated_at
FROM payroll.payroll_results pr
JOIN payroll.payroll_periods pp ON pp.id = pr.payroll_period_id
WHERE pr.tenant_id = $1
  AND pr.employee_id = $2
  AND ($3::integer IS NULL OR pp.year = $3::integer)
  AND ($4::platform.uuid_v7 IS NULL OR pr.id < $4::platform.uuid_v7)
ORDER BY pr.id DESC
LIMIT $5
`

type ListPayrollHistoryParams struct {
	TenantID   uuid.UUID  `json:"tenant_id"`
	EmployeeID uuid.UUID  `json:"employee_id"`
	Year       *int32     `json:"year"`
	CursorID   *uuid.UUID `json:"cursor_id"`
	Limit      int32      `json:"limit"`
}

type ListPayrollHistoryRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CompanyID         uuid.UUID          `json:"company_id"`
	PayrollPeriodID   uuid.UUID          `json:"payroll_period_id"`
	EmployeeID        uuid.UUID          `json:"employee_id"`
	EmploymentID      uuid.UUID          `json:"employment_id"`
	GrossIncome       int64              `json:"gross_income"`
	TaxableIncome     int64              `json:"taxable_income"`
	TakeHomePay       int64              `json:"take_home_pay"`
	FinalizedAt       pgtype.Timestamptz `json:"finalized_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PeriodYear        int32              `json:"period_year"`
	PeriodMonth       int32              `json:"period_month"`
	PeriodStatus      string             `json:"period_status"`
	PeriodOpenedAt    pgtype.Timestamptz `json:"period_opened_at"`
	PeriodFinalizedAt pgtype.Timestamptz `json:"period_finalized_at"`
	PeriodCreatedAt   pgtype.Timestamptz `json:"period_created_at"`
	PeriodUpdatedAt   pgtype.Timestamptz `json:"period_updated_at"`
}

func (q *Queries) ListPayrollHistory(ctx context.Context, arg ListPayrollHistoryParams) ([]ListPayrollHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPayrollHistory,
		arg.TenantID,
		arg.EmployeeID,
		arg.Year,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayrollHistoryRow
	for rows.Next() {
		var i ListPayrollHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyID,
			&i.PayrollPeriodID,
			&i.EmployeeID,
			&i.EmploymentID,
			&i.GrossIncome,
			&i.TaxableIncome,
			&i.TakeHomePay,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.PeriodStatus,
			&i.PeriodOpenedAt,
			&i.PeriodFinalizedAt,
			&i.PeriodCreatedAt,
			&i.PeriodUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollPeriods = `-- name: ListPayrollPeriods :many
SELECT id, tenant_id, company_id, year, month, status, opened_at, finalized_at, created_at, updated_at
FROM payroll.payroll_periods
WHERE tenant_id = $1
  AND ($2::platform.uuid_v7 IS NULL OR company_id = $2::platform.uuid_v7)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::platform.uuid_v7 IS NULL OR id < $4::platform.uuid_v7)
ORDER BY id DESC
LIMIT $5
`

type ListPayrollPeriodsParams struct {
	TenantID  uuid.UUID  `json:"tenant_id"`
	CompanyID *uuid.UUID `json:"company_id"`
	Status    *string    `json:"status"`
	CursorID  *uuid.UUID `json:"cursor_id"`
	Limit     int32      `json:"limit"`
}

func (q *Queries) ListPayrollPeriods(ctx context.Context, arg ListPayrollPeriodsParams) ([]PayrollPayrollPeriod, error) {
	rows, err := q.db.Query(ctx, listPayrollPeriods,
		arg.TenantID,
		arg.CompanyID,
		arg.Status,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollPayrollPeriod
	for rows.Next() {
		var i PayrollPayrollPeriod
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompanyID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.OpenedAt,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollResultItems = `-- name: ListPayrollResultItems :many
SELECT id, payroll_result_id, component_code, component_type, amount, created_at, updated_at
FROM payroll.payroll_result_items
WHERE payroll_result_id = $1
ORDER BY component_code ASC, id ASC
`

func (q *Queries) ListPayrollResultItems(ctx context.Context, payrollResultID uuid.UUID) ([]PayrollPayrollResultItem, error) {
	rows, err := q.db.Query(ctx, listPayrollResultItems, payrollResultID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollPayrollResultItem
	for rows.Next() {
		var i PayrollPayrollResultItem
		if err := rows.Scan(
			&i.ID,
			&i.PayrollResultID,
			&i.ComponentCode,
			&i.ComponentType,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPayrollRunSequence = `-- name: NextPayrollRunSequence :one
SELECT COALESCE(MAX(sequence_no), 0)::integer + 1 AS next_sequence
FROM payroll.payroll_runs
WHERE tenant_id = $1 AND company_id = $2
  AND payroll_period_id = $3 AND run_type = $4
`

type NextPayrollRunSequenceParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	CompanyID       uuid.UUID `json:"company_id"`
	PayrollPeriodID uuid.UUID `json:"payroll_period_id"`
	RunType         string    `json:"run_type"`
}

func (q *Queries) NextPayrollRunSequence(ctx context.Context, arg NextPayrollRunSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextPayrollRunSequence,
		arg.TenantID,
		arg.CompanyID,
		arg.PayrollPeriodID,
		arg.RunType,
	)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}
